mode = "dark"

accent = "#eb9a75"
selection = "#4f3124"
muted = "#816c63"

background = "#120805"
dark_background = "#0e0604"
darker_background = "#090403"
lighter_background = "#221611"

foreground = "#edddd7"
dark_foreground = "#9a8c87"
light_foreground = "#d8c6bf"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(eb9a75ee) rgba(c99b65ee) 45deg"
hyprland_inactive_border = "rgba(816c63aa)"

red = "#c87a6d"
yellow = "#efb87c"
orange = "#de9871"
green = "#b0ad81"
cyan = "#b2cecf"
blue = "#be947e"
magenta = "#d79ca0"
brown = "#865634"

bright_red = "#d69489"
bright_yellow = "#fdd2a4"
bright_green = "#c5c39f"
bright_cyan = "#cde4e5"
bright_blue = "#d0ac9a"
bright_magenta = "#e7b6b8"
