mode = "light"

accent = "#0c74b5"
selection = "#bad8ed"
muted = "#6d7c8c"

background = "#ebf4fd"
dark_background = "#dceaf9"
darker_background = "#cedded"
lighter_background = "#d2e2f4"

foreground = "#212f3e"
dark_foreground = "#576574"
light_foreground = "#404f5e"
bright_foreground = "#0c1722"

hyprland_active_border = "rgba(0c74b5ee) rgba(897549ee) 45deg"
hyprland_inactive_border = "rgba(6d7c8caa)"

red = "#9c3c38"
yellow = "#866b2d"
orange = "#965520"
green = "#2a7a62"
cyan = "#0b6870"
blue = "#0b61ac"
magenta = "#2e7796"
brown = "#774826"

bright_red = "#8a2727"
bright_yellow = "#745813"
bright_green = "#046750"
bright_cyan = "#0b555c"
bright_blue = "#045091"
bright_magenta = "#0b6382"
