mode = "dark"

accent = "#79c77c"
selection = "#254027"
muted = "#67766a"

background = "#050b06"
dark_background = "#040805"
darker_background = "#030603"
lighter_background = "#111913"

foreground = "#dae5db"
dark_foreground = "#89928a"
light_foreground = "#c2cec4"
bright_foreground = "#f2f9f3"

hyprland_active_border = "rgba(79c77cee) rgba(cd995cee) 45deg"
hyprland_inactive_border = "rgba(67766aaa)"

red = "#d67069"
yellow = "#cedc69"
orange = "#e7a145"
green = "#81ce70"
cyan = "#77e0d3"
blue = "#6bb797"
magenta = "#d4bc79"
brown = "#865634"

bright_red = "#e38d86"
bright_yellow = "#e5f297"
bright_green = "#a2e194"
bright_cyan = "#a1f4e8"
bright_blue = "#8ecaaf"
bright_magenta = "#e7d39d"
