mode = "light"

accent = "#3970b3"
selection = "#c3d7ee"
muted = "#6e7c8a"

background = "#eaf4fe"
dark_background = "#deeaf6"
darker_background = "#d1ddea"
lighter_background = "#d5e2f0"

foreground = "#222f3c"
dark_foreground = "#586573"
light_foreground = "#424e5c"
bright_foreground = "#0d1721"

hyprland_active_border = "rgba(3970b3ee) rgba(8c7349ee) 45deg"
hyprland_inactive_border = "rgba(6e7c8aaa)"

red = "#9c3c38"
yellow = "#866b2d"
orange = "#965520"
green = "#2a7a62"
cyan = "#00667e"
blue = "#2460a7"
magenta = "#39749b"
brown = "#774826"

bright_red = "#8a2727"
bright_yellow = "#725711"
bright_green = "#046750"
bright_cyan = "#015468"
bright_blue = "#094e96"
bright_magenta = "#226188"
