mode = "light"

accent = "#c33740"
selection = "#f0c7c1"
muted = "#8b7667"

background = "#fdf0e6"
dark_background = "#f8e4d6"
darker_background = "#ecd7c7"
lighter_background = "#f3dbcb"

foreground = "#3c291a"
dark_foreground = "#715f53"
light_foreground = "#5c493b"
bright_foreground = "#201208"

hyprland_active_border = "rgba(c33740ee) rgba(158561ee) 45deg"
hyprland_inactive_border = "rgba(8b7667aa)"

red = "#a40021"
yellow = "#866b2d"
orange = "#974b00"
green = "#0e7e53"
cyan = "#074e37"
blue = "#046659"
magenta = "#a1456e"
brown = "#774826"

bright_red = "#88001a"
bright_yellow = "#725711"
bright_green = "#006943"
bright_cyan = "#003d29"
bright_blue = "#045348"
bright_magenta = "#8f315d"
