mode = "light"

accent = "#ac5701"
selection = "#edceb1"
muted = "#897765"

background = "#fff0e2"
dark_background = "#f7e5d5"
darker_background = "#ebd8c6"
lighter_background = "#f1dcc9"

foreground = "#3b2a19"
dark_foreground = "#706052"
light_foreground = "#5b4939"
bright_foreground = "#1f1307"

hyprland_active_border = "rgba(ac5701ee) rgba(b15038ee) 45deg"
hyprland_inactive_border = "rgba(897765aa)"

red = "#9c1f14"
yellow = "#96650a"
orange = "#994901"
green = "#606f28"
cyan = "#6e5b30"
blue = "#9b4806"
magenta = "#93434c"
brown = "#774826"

bright_red = "#860500"
bright_yellow = "#7c5306"
bright_green = "#4f5e0e"
bright_cyan = "#5e4a1d"
bright_blue = "#823b03"
bright_magenta = "#81303b"
