mode = "dark"

accent = "#abbb67"
selection = "#403e20"
muted = "#816d5e"

background = "#170d05"
dark_background = "#110a04"
darker_background = "#0c0703"
lighter_background = "#271b11"

foreground = "#edded3"
dark_foreground = "#9c8f85"
light_foreground = "#d7c7bb"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(abbb67ee) rgba(cd995cee) 45deg"
hyprland_inactive_border = "rgba(816d5eaa)"

red = "#df8071"
yellow = "#eed780"
orange = "#efa969"
green = "#96c979"
cyan = "#addfbd"
blue = "#cca17e"
magenta = "#df9da1"
brown = "#865634"

bright_red = "#ec9c8f"
bright_yellow = "#ffefb1"
bright_green = "#b2dd9c"
bright_cyan = "#caf4d7"
bright_blue = "#ddb99c"
bright_magenta = "#efb7ba"
