mode = "light"

accent = "#826b41"
selection = "#d6d5d2"
muted = "#757a86"

background = "#eef3fb"
dark_background = "#e4e9f3"
darker_background = "#d6dbe6"
lighter_background = "#dbe0ec"

foreground = "#292e38"
dark_foreground = "#5d6370"
light_foreground = "#484d57"
bright_foreground = "#12161e"

hyprland_active_border = "rgba(826b41ee) rgba(497893ee) 45deg"
hyprland_inactive_border = "rgba(757a86aa)"

red = "#894e39"
yellow = "#856b39"
orange = "#895c34"
green = "#4d775c"
cyan = "#225c6c"
blue = "#40668d"
magenta = "#6f6385"
brown = "#774826"

bright_red = "#783c27"
bright_yellow = "#715721"
bright_green = "#396549"
bright_cyan = "#074b5c"
bright_blue = "#2e557c"
bright_magenta = "#5e5274"
