mode = "dark"

accent = "#ed9c55"
selection = "#52331b"
muted = "#836c61"

background = "#160a05"
dark_background = "#110804"
darker_background = "#0b0503"
lighter_background = "#261811"

foreground = "#efddd5"
dark_foreground = "#9d8d86"
light_foreground = "#d9c6be"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(ed9c55ee) rgba(ebe5cfee) 45deg"
hyprland_inactive_border = "rgba(836c61aa)"

red = "#ec8274"
yellow = "#ffb668"
orange = "#f99b6a"
green = "#9ebe6d"
cyan = "#4fcdcd"
blue = "#61b5e8"
magenta = "#e18bbc"
brown = "#865634"

bright_red = "#f8a092"
bright_yellow = "#fed6ae"
bright_green = "#b7d390"
bright_cyan = "#82e0df"
bright_blue = "#88caf5"
bright_magenta = "#f0a7d0"
