mode = "dark"

accent = "#ecd4ab"
selection = "#4a453c"
muted = "#6c727d"

background = "#0b0d11"
dark_background = "#080a0d"
darker_background = "#060709"
lighter_background = "#191c21"

foreground = "#dde1eb"
dark_foreground = "#8d9098"
light_foreground = "#c5cbd5"
bright_foreground = "#f3f7fe"

hyprland_active_border = "rgba(ecd4abee) rgba(80abc5ee) 45deg"
hyprland_inactive_border = "rgba(6c727daa)"

red = "#d1947f"
yellow = "#f5daaa"
orange = "#e5b690"
green = "#a0caad"
cyan = "#9fd4e6"
blue = "#89afd6"
magenta = "#bcb1d3"
brown = "#865634"

bright_red = "#e1ad9b"
bright_yellow = "#ffeccb"
bright_green = "#bcdfc7"
bright_cyan = "#bee9f8"
bright_blue = "#a6c5e5"
bright_magenta = "#d2c8e5"
