mode = "light"

accent = "#98630c"
selection = "#e6d1b4"
muted = "#877767"

background = "#fcf0e4"
dark_background = "#f4e6d7"
darker_background = "#e8d8c9"
lighter_background = "#eeddcc"

foreground = "#392b1b"
dark_foreground = "#6f6051"
light_foreground = "#594a3b"
bright_foreground = "#1f1308"

hyprland_active_border = "rgba(98630cee) rgba(a7593dee) 45deg"
hyprland_inactive_border = "rgba(877767aa)"

red = "#983124"
yellow = "#7c5700"
orange = "#8c4704"
green = "#717227"
cyan = "#457774"
blue = "#724627"
magenta = "#944d5f"
brown = "#774826"

bright_red = "#86190f"
bright_yellow = "#664804"
bright_green = "#5d5e02"
bright_cyan = "#2f6360"
bright_blue = "#613513"
bright_magenta = "#833b4e"
