mode = "dark"

accent = "#e1a263"
selection = "#533a22"
muted = "#826f5f"

background = "#1c1109"
dark_background = "#150d07"
darker_background = "#0e0905"
lighter_background = "#2c2016"

foreground = "#edded3"
dark_foreground = "#9e9086"
light_foreground = "#d7c7bb"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(e1a263ee) rgba(e6857eee) 45deg"
hyprland_inactive_border = "rgba(826f5faa)"

red = "#df8071"
yellow = "#fbc77c"
orange = "#f1a270"
green = "#b5be82"
cyan = "#a6d6d2"
blue = "#cea081"
magenta = "#eaa6aa"
brown = "#885836"

bright_red = "#ec9c8f"
bright_yellow = "#fee3c0"
bright_green = "#ccd3a2"
bright_cyan = "#c4ebe8"
bright_blue = "#dfb89e"
bright_magenta = "#f9c0c3"
