mode = "light"

accent = "#a95a00"
selection = "#eacfb1"
muted = "#877866"

background = "#fcf0e3"
dark_background = "#f4e6d6"
darker_background = "#e8d9c7"
lighter_background = "#eeddca"

foreground = "#392b19"
dark_foreground = "#6e6151"
light_foreground = "#584a3a"
bright_foreground = "#1e1407"

hyprland_active_border = "rgba(a95a00ee) rgba(a35a4eee) 45deg"
hyprland_inactive_border = "rgba(877866aa)"

red = "#953a1c"
yellow = "#956300"
orange = "#974f03"
green = "#676e2f"
cyan = "#567273"
blue = "#835636"
magenta = "#743736"
brown = "#774826"

bright_red = "#832500"
bright_yellow = "#7c5302"
bright_green = "#565d19"
bright_cyan = "#436061"
bright_blue = "#724523"
bright_magenta = "#632526"
