mode = "light"

accent = "#a65c03"
selection = "#e7d0b4"
muted = "#847869"

background = "#f9f1e6"
dark_background = "#f1e7da"
darker_background = "#e4dacc"
lighter_background = "#eaded0"

foreground = "#372c1d"
dark_foreground = "#6c6153"
light_foreground = "#564b3d"
bright_foreground = "#1d1409"

hyprland_active_border = "rgba(a65c03ee) rgba(597d51ee) 45deg"
hyprland_inactive_border = "rgba(847869aa)"

red = "#a54745"
yellow = "#9d6000"
orange = "#a55227"
green = "#487b37"
cyan = "#047c79"
blue = "#1e689d"
magenta = "#974a79"
brown = "#774826"

bright_red = "#933334"
bright_yellow = "#824e00"
bright_green = "#33671f"
bright_cyan = "#006663"
bright_blue = "#01578a"
bright_magenta = "#853768"
