mode = "light"

accent = "#c33839"
selection = "#f1c7bf"
muted = "#897669"

background = "#feefe5"
dark_background = "#f6e5d9"
darker_background = "#ead7ca"
lighter_background = "#f0dcce"

foreground = "#3b2a1d"
dark_foreground = "#715f53"
light_foreground = "#5a493d"
bright_foreground = "#201309"

hyprland_active_border = "rgba(c33839ee) rgba(a06024ee) 45deg"
hyprland_inactive_border = "rgba(897669aa)"

red = "#9e0016"
yellow = "#a15800"
orange = "#a03a00"
green = "#4a7840"
cyan = "#916256"
blue = "#973f4a"
magenta = "#8d2b59"
brown = "#774826"

bright_red = "#820010"
bright_yellow = "#894a00"
bright_green = "#37652c"
bright_cyan = "#7e4f43"
bright_blue = "#852b39"
bright_magenta = "#7b1249"
