mode = "dark"

accent = "#e4a249"
selection = "#503518"
muted = "#836c60"

background = "#160a05"
dark_background = "#110804"
darker_background = "#0b0503"
lighter_background = "#261810"

foreground = "#eeddd4"
dark_foreground = "#9c8d85"
light_foreground = "#d8c6bd"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(e4a249ee) rgba(da8f74ee) 45deg"
hyprland_inactive_border = "rgba(836c60aa)"

red = "#dd7767"
yellow = "#fec766"
orange = "#f49d5e"
green = "#c1c37e"
cyan = "#9fcfcb"
blue = "#cea081"
magenta = "#e299a9"
brown = "#865634"

bright_red = "#ea9486"
bright_yellow = "#fee4ba"
bright_green = "#d6d9a1"
bright_cyan = "#bde4e0"
bright_blue = "#dfb89e"
bright_magenta = "#f2b4c0"
