mode = "dark"

accent = "#f49191"
selection = "#583231"
muted = "#856a68"

background = "#1b0d0c"
dark_background = "#140a09"
darker_background = "#0e0706"
lighter_background = "#2c1c1a"

foreground = "#f0dcda"
dark_foreground = "#9f8d8c"
light_foreground = "#dac5c3"
bright_foreground = "#fef4f3"

hyprland_active_border = "rgba(f49191ee) rgba(e6cda5ee) 45deg"
hyprland_inactive_border = "rgba(856a68aa)"

red = "#e68581"
yellow = "#edc06a"
orange = "#f1a06c"
green = "#9dbe79"
cyan = "#63cbc8"
blue = "#71b3e2"
magenta = "#da8fbc"
brown = "#865634"

bright_red = "#f3a19d"
bright_yellow = "#fed895"
bright_green = "#b7d299"
bright_cyan = "#8edfdb"
bright_blue = "#93c8f0"
bright_magenta = "#e9aacf"
