mode = "dark"

accent = "#f49191"
selection = "#583231"
muted = "#856a68"

background = "#1b0d0c"
dark_background = "#140a09"
darker_background = "#0e0706"
lighter_background = "#2c1c1a"

foreground = "#f0dcda"
dark_foreground = "#9f8d8c"
light_foreground = "#dac5c3"
bright_foreground = "#fef4f3"

hyprland_active_border = "rgba(f49191ee) rgba(e6cda5ee) 45deg"
hyprland_inactive_border = "rgba(856a68aa)"

red = "#da6b6e"
yellow = "#f2cc7a"
orange = "#ef9a63"
green = "#98c5a0"
cyan = "#ecdcc1"
blue = "#dd939e"
magenta = "#eba6c6"
brown = "#865634"

bright_red = "#e78989"
bright_yellow = "#fee5b3"
bright_green = "#b4d9bb"
bright_cyan = "#faedd6"
bright_blue = "#ecaeb6"
bright_magenta = "#fbc1db"
