mode = "dark"

accent = "#e79c7e"
selection = "#533428"
muted = "#866a62"

background = "#1a0b07"
dark_background = "#140805"
darker_background = "#0d0604"
lighter_background = "#2b1913"

foreground = "#f1dcd6"
dark_foreground = "#9f8d87"
light_foreground = "#dbc5be"
bright_foreground = "#fdf5f2"

hyprland_active_border = "rgba(e79c7eee) rgba(e8ddc1ee) 45deg"
hyprland_inactive_border = "rgba(866a62aa)"

red = "#df7f78"
yellow = "#f7d293"
orange = "#f0a87a"
green = "#b2be93"
cyan = "#b3d9db"
blue = "#d5a08d"
magenta = "#eeabba"
brown = "#865634"

bright_red = "#ec9b94"
bright_yellow = "#feecce"
bright_green = "#c9d3b0"
bright_cyan = "#cfeff0"
bright_blue = "#e6b9a9"
bright_magenta = "#fec6d1"
