mode = "light"

accent = "#bf4031"
selection = "#e1cccf"
muted = "#6e7d87"

background = "#eaf4fb"
dark_background = "#dfeaf3"
darker_background = "#d1dde6"
lighter_background = "#d5e2ec"

foreground = "#22303a"
dark_foreground = "#576570"
light_foreground = "#414f59"
bright_foreground = "#0d171f"

hyprland_active_border = "rgba(bf4031ee) rgba(3f7c8aee) 45deg"
hyprland_inactive_border = "rgba(6e7d87aa)"

red = "#b33827"
yellow = "#8a690a"
orange = "#9f5603"
green = "#437b21"
cyan = "#067b7f"
blue = "#0067ab"
magenta = "#9b4481"
brown = "#774826"

bright_red = "#a11e0c"
bright_yellow = "#745700"
bright_green = "#306803"
bright_cyan = "#00666a"
bright_blue = "#005690"
bright_magenta = "#893071"
