mode = "light"

accent = "#bf4031"
selection = "#e1cccf"
muted = "#6e7d87"

background = "#eaf4fb"
dark_background = "#dfeaf3"
darker_background = "#d1dde6"
lighter_background = "#d5e2ec"

foreground = "#22303a"
dark_foreground = "#576570"
light_foreground = "#414f59"
bright_foreground = "#0d171f"

hyprland_active_border = "rgba(bf4031ee) rgba(3f7c8aee) 45deg"
hyprland_inactive_border = "rgba(6e7d87aa)"

red = "#a01700"
yellow = "#8c690a"
orange = "#924f08"
green = "#52754b"
cyan = "#35768e"
blue = "#415d9d"
magenta = "#994d6d"
brown = "#774826"

bright_red = "#831200"
bright_yellow = "#765702"
bright_green = "#416439"
bright_cyan = "#1b637b"
bright_blue = "#304b8c"
bright_magenta = "#873a5c"
