mode = "dark"

accent = "#eb9e41"
selection = "#573817"
muted = "#846e5d"

background = "#1d1107"
dark_background = "#160d05"
darker_background = "#0f0904"
lighter_background = "#2e1f13"

foreground = "#eeded1"
dark_foreground = "#9f9084"
light_foreground = "#d8c7ba"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(eb9e41ee) rgba(e7d6abee) 45deg"
hyprland_inactive_border = "rgba(846e5daa)"

red = "#e77b60"
yellow = "#ffbc64"
orange = "#f69a5c"
green = "#babc80"
cyan = "#ecddb9"
blue = "#d39e7a"
magenta = "#e49a9f"
brown = "#885836"

bright_red = "#f39982"
bright_yellow = "#ffdbaf"
bright_green = "#cfd2a0"
bright_cyan = "#faeed0"
bright_blue = "#e3b799"
bright_magenta = "#f4b4b8"
