mode = "dark"

accent = "#ef996c"
selection = "#543323"
muted = "#836c60"

background = "#180c06"
dark_background = "#120905"
darker_background = "#0c0603"
lighter_background = "#281a13"

foreground = "#eeddd4"
dark_foreground = "#9d8e86"
light_foreground = "#d8c6bd"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(ef996cee) rgba(dc8b8bee) 45deg"
hyprland_inactive_border = "rgba(836c60aa)"

red = "#d07b6a"
yellow = "#f5bb75"
orange = "#e69a6c"
green = "#b0b27f"
cyan = "#b5d1d2"
blue = "#c19780"
magenta = "#da9fa0"
brown = "#865634"

bright_red = "#de9687"
bright_yellow = "#ffd6a8"
bright_green = "#c6c89d"
bright_cyan = "#d0e7e8"
bright_blue = "#d2af9c"
bright_magenta = "#eab9b9"
