mode = "light"

accent = "#a5573c"
selection = "#e3ccc1"
muted = "#83766b"

background = "#f5ede6"
dark_background = "#ece3da"
darker_background = "#e0d5cd"
lighter_background = "#e5dad1"

foreground = "#372b21"
dark_foreground = "#6d6156"
light_foreground = "#564b40"
bright_foreground = "#1d140c"

hyprland_active_border = "rgba(a5573cee) rgba(976539ee) 45deg"
hyprland_inactive_border = "rgba(83766baa)"

red = "#9d4f3d"
yellow = "#956016"
orange = "#9b5729"
green = "#5b7436"
cyan = "#127876"
blue = "#2c6992"
magenta = "#925074"
brown = "#774826"

bright_red = "#8b3c2a"
bright_yellow = "#7f4e01"
bright_green = "#496120"
bright_cyan = "#006462"
bright_blue = "#145881"
bright_magenta = "#803e63"
