mode = "light"

accent = "#a5573c"
selection = "#e3ccc1"
muted = "#83766b"

background = "#f5ede6"
dark_background = "#ece3da"
darker_background = "#e0d5cd"
lighter_background = "#e5dad1"

foreground = "#372b21"
dark_foreground = "#6d6156"
light_foreground = "#564b40"
bright_foreground = "#1d140c"

hyprland_active_border = "rgba(a5573cee) rgba(976539ee) 45deg"
hyprland_inactive_border = "rgba(83766baa)"

red = "#823c35"
yellow = "#946129"
orange = "#8d4d2d"
green = "#69623e"
cyan = "#557173"
blue = "#634132"
magenta = "#5a2e34"
brown = "#774826"

bright_red = "#702a24"
bright_yellow = "#804c09"
bright_green = "#58522c"
bright_cyan = "#415d5f"
bright_blue = "#533121"
bright_magenta = "#4a1e25"
