mode = "light"

accent = "#a7542c"
selection = "#e5cbbb"
muted = "#837467"

background = "#f7ece3"
dark_background = "#efe2d6"
darker_background = "#e2d5c8"
lighter_background = "#e8d9cc"

foreground = "#382b1e"
dark_foreground = "#6f6053"
light_foreground = "#584a3d"
bright_foreground = "#1e140a"

hyprland_active_border = "rgba(a7542cee) rgba(966628ee) 45deg"
hyprland_inactive_border = "rgba(837467aa)"

red = "#a5483a"
yellow = "#926208"
orange = "#9f541e"
green = "#56742a"
cyan = "#007977"
blue = "#1c6999"
magenta = "#964b78"
brown = "#774826"

bright_red = "#933527"
bright_yellow = "#785007"
bright_green = "#43620e"
bright_cyan = "#006463"
bright_blue = "#005885"
bright_magenta = "#843867"
