mode = "light"

accent = "#a7542c"
selection = "#e5cbbb"
muted = "#837467"

background = "#f7ece3"
dark_background = "#efe2d6"
darker_background = "#e2d5c8"
lighter_background = "#e8d9cc"

foreground = "#382b1e"
dark_foreground = "#6f6053"
light_foreground = "#584a3d"
bright_foreground = "#1e140a"

hyprland_active_border = "rgba(a7542cee) rgba(966628ee) 45deg"
hyprland_inactive_border = "rgba(837467aa)"

red = "#883b30"
yellow = "#976019"
orange = "#924c23"
green = "#696538"
cyan = "#567173"
blue = "#69412c"
magenta = "#612d32"
brown = "#774826"

bright_red = "#76281e"
bright_yellow = "#7f4d01"
bright_green = "#585425"
bright_cyan = "#415d5f"
bright_blue = "#58301b"
bright_magenta = "#501c23"
