mode = "light"

accent = "#657303"
selection = "#d7d2af"
muted = "#847665"

background = "#f7eddf"
dark_background = "#efe2d3"
darker_background = "#e3d5c4"
lighter_background = "#e9dac8"

foreground = "#382b1a"
dark_foreground = "#6e6151"
light_foreground = "#584b3a"
bright_foreground = "#1e1407"

hyprland_active_border = "rgba(657303ee) rgba(9a6418ee) 45deg"
hyprland_inactive_border = "rgba(847665aa)"

red = "#98392d"
yellow = "#7f6a00"
orange = "#915202"
green = "#457822"
cyan = "#437656"
blue = "#835835"
magenta = "#915157"
brown = "#774826"

bright_red = "#862419"
bright_yellow = "#6a5805"
bright_green = "#336505"
bright_cyan = "#2e6443"
bright_blue = "#724721"
bright_magenta = "#803f45"
