mode = "light"

accent = "#906606"
selection = "#e3d2b2"
muted = "#857866"

background = "#fbf1e3"
dark_background = "#f2e7d6"
darker_background = "#e6dac8"
lighter_background = "#ebdecb"

foreground = "#372c1a"
dark_foreground = "#6d6150"
light_foreground = "#574b3a"
bright_foreground = "#1d1407"

hyprland_active_border = "rgba(906606ee) rgba(a65b1eee) 45deg"
hyprland_inactive_border = "rgba(857866aa)"

red = "#9b380e"
yellow = "#8e6900"
orange = "#945403"
green = "#687027"
cyan = "#5d5528"
blue = "#825204"
magenta = "#803a36"
brown = "#774826"

bright_red = "#832a00"
bright_yellow = "#755600"
bright_green = "#575f09"
bright_cyan = "#4d4514"
bright_blue = "#6d4300"
bright_magenta = "#6e2826"
