mode = "dark"

accent = "#e8cf8c"
selection = "#574b31"
muted = "#817260"

background = "#1f170d"
dark_background = "#17110a"
darker_background = "#100c07"
lighter_background = "#2f261a"

foreground = "#eadfd2"
dark_foreground = "#9d9387"
light_foreground = "#d4c8ba"
bright_foreground = "#fbf6f0"

hyprland_active_border = "rgba(e8cf8cee) rgba(cf976aee) 45deg"
hyprland_inactive_border = "rgba(817260aa)"

red = "#dc8c80"
yellow = "#e4c379"
orange = "#e6a575"
green = "#a3bc7e"
cyan = "#71c9c7"
blue = "#7ab2dc"
magenta = "#d693b7"
brown = "#8b5b39"

bright_red = "#eaa79c"
bright_yellow = "#f6db9f"
bright_green = "#bcd19e"
bright_cyan = "#97dddb"
bright_blue = "#9ac7eb"
bright_magenta = "#e6aecb"
