mode = "dark"

accent = "#e3a165"
selection = "#5b4028"
muted = "#897464"

background = "#261a10"
dark_background = "#1d140c"
darker_background = "#130d08"
lighter_background = "#38291e"

foreground = "#eeded2"
dark_foreground = "#a29488"
light_foreground = "#d8c7ba"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(e3a165ee) rgba(afa673ee) 45deg"
hyprland_inactive_border = "rgba(897464aa)"

red = "#dd8364"
yellow = "#fcc771"
orange = "#f0a465"
green = "#b5bf7b"
cyan = "#bbd7d9"
blue = "#cda07f"
magenta = "#eaa7a1"
brown = "#8e5d3b"

bright_red = "#ea9f84"
bright_yellow = "#fee4bd"
bright_green = "#ccd49d"
bright_cyan = "#d6edee"
bright_blue = "#deb89d"
bright_magenta = "#fac1bc"
