mode = "dark"

accent = "#e3a165"
selection = "#5b4028"
muted = "#897464"

background = "#261a10"
dark_background = "#1d140c"
darker_background = "#130d08"
lighter_background = "#38291e"

foreground = "#eeded2"
dark_foreground = "#a29488"
light_foreground = "#d8c7ba"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(e3a165ee) rgba(afa673ee) 45deg"
hyprland_inactive_border = "rgba(897464aa)"

red = "#e48681"
yellow = "#f9b971"
orange = "#f39e75"
green = "#adba6c"
cyan = "#5eccc8"
blue = "#71b2e6"
magenta = "#d98fbf"
brown = "#8e5d3b"

bright_red = "#f1a29d"
bright_yellow = "#fed6ac"
bright_green = "#c4cf90"
bright_cyan = "#8bdfdc"
bright_blue = "#93c8f3"
bright_magenta = "#e9aad2"
