mode = "light"

accent = "#c7303c"
selection = "#f2c5c0"
muted = "#897669"

background = "#feefe5"
dark_background = "#f6e5d9"
darker_background = "#ead7ca"
lighter_background = "#f0dcce"

foreground = "#3b2a1d"
dark_foreground = "#715f53"
light_foreground = "#5a493d"
bright_foreground = "#201309"

hyprland_active_border = "rgba(c7303cee) rgba(3e8442ee) 45deg"
hyprland_inactive_border = "rgba(897669aa)"

red = "#9c0627"
yellow = "#8c6908"
orange = "#964800"
green = "#2c7933"
cyan = "#6c7245"
blue = "#306d55"
magenta = "#9f4164"
brown = "#774826"

bright_red = "#80031e"
bright_yellow = "#735609"
bright_green = "#0f681e"
bright_cyan = "#585e30"
bright_blue = "#185c44"
bright_magenta = "#8d2d52"
