mode = "dark"

accent = "#dea45f"
selection = "#574127"
muted = "#847664"

background = "#231b11"
dark_background = "#1a140d"
darker_background = "#120e09"
lighter_background = "#342b1f"

foreground = "#eae0d2"
dark_foreground = "#9e9589"
light_foreground = "#d4c9ba"
bright_foreground = "#fbf6f0"

hyprland_active_border = "rgba(dea45fee) rgba(e9ddc1ee) 45deg"
hyprland_inactive_border = "rgba(847664aa)"

red = "#dc8b87"
yellow = "#efbe72"
orange = "#eca278"
green = "#9cbd82"
cyan = "#6fc9c7"
blue = "#77b2dc"
magenta = "#d593ba"
brown = "#8e5d3b"

bright_red = "#eba6a2"
bright_yellow = "#fed79e"
bright_green = "#b6d2a1"
bright_cyan = "#96dddb"
bright_blue = "#97c7ea"
bright_magenta = "#e5aece"
