mode = "dark"

accent = "#fc8999"
selection = "#562d33"
muted = "#846a6d"

background = "#16090b"
dark_background = "#110708"
darker_background = "#0b0506"
lighter_background = "#271719"

foreground = "#f0dcde"
dark_foreground = "#9d8c8e"
light_foreground = "#dac4c7"
bright_foreground = "#fdf4f5"

hyprland_active_border = "rgba(fc8999ee) rgba(d688b4ee) 45deg"
hyprland_inactive_border = "rgba(846a6daa)"

red = "#de6674"
yellow = "#fdbc6f"
orange = "#f58f66"
green = "#a4c386"
cyan = "#fed2cb"
blue = "#d28bb3"
magenta = "#fb93b4"
brown = "#865634"

bright_red = "#ea868e"
bright_yellow = "#fddbb4"
bright_green = "#bed8a5"
bright_cyan = "#fee9e5"
bright_blue = "#e2a6c7"
bright_magenta = "#feb7cc"
