mode = "dark"

accent = "#fe8b83"
selection = "#5b332d"
muted = "#826e64"

background = "#1b110c"
dark_background = "#140d09"
darker_background = "#0e0906"
lighter_background = "#2c2019"

foreground = "#edded6"
dark_foreground = "#9d9089"
light_foreground = "#d7c7be"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(fe8b83ee) rgba(6bb5a2ee) 45deg"
hyprland_inactive_border = "rgba(826e64aa)"

red = "#f47b74"
yellow = "#ecc258"
orange = "#f99c55"
green = "#9ac06c"
cyan = "#50d0ba"
blue = "#68b2ef"
magenta = "#e08ac2"
brown = "#885836"

bright_red = "#fd9c94"
bright_yellow = "#fdda88"
bright_green = "#b4d490"
bright_cyan = "#83e3d1"
bright_blue = "#8cc8fb"
bright_magenta = "#eea7d4"
