mode = "light"

accent = "#7e6934"
selection = "#ddcfba"
muted = "#847564"

background = "#f8ece0"
dark_background = "#f0e2d3"
darker_background = "#e4d5c5"
lighter_background = "#e9d9c8"

foreground = "#392b1b"
dark_foreground = "#6f6151"
light_foreground = "#584a3b"
bright_foreground = "#1e1407"

hyprland_active_border = "rgba(7e6934ee) rgba(bb4441ee) 45deg"
hyprland_inactive_border = "rgba(847564aa)"

red = "#9c3428"
yellow = "#81692a"
orange = "#93510e"
green = "#59743d"
cyan = "#427370"
blue = "#86563b"
magenta = "#79343c"
brown = "#774826"

bright_red = "#8a1d13"
bright_yellow = "#6d550c"
bright_green = "#476128"
bright_cyan = "#2d615d"
bright_blue = "#754528"
bright_magenta = "#68212c"
