mode = "light"

accent = "#7e6934"
selection = "#ddcfba"
muted = "#847564"

background = "#f8ece0"
dark_background = "#f0e2d3"
darker_background = "#e4d5c5"
lighter_background = "#e9d9c8"

foreground = "#392b1b"
dark_foreground = "#6f6151"
light_foreground = "#584a3b"
bright_foreground = "#1e1407"

hyprland_active_border = "rgba(7e6934ee) rgba(bb4441ee) 45deg"
hyprland_inactive_border = "rgba(847564aa)"

red = "#af3c38"
yellow = "#866703"
orange = "#9e5408"
green = "#517618"
cyan = "#067975"
blue = "#0769a1"
magenta = "#9b457e"
brown = "#774826"

bright_red = "#9d2425"
bright_yellow = "#705506"
bright_green = "#406300"
bright_cyan = "#026461"
bright_blue = "#085786"
bright_magenta = "#89326d"
