mode = "light"

accent = "#a65a3b"
selection = "#eacfc0"
muted = "#8a7666"

background = "#fdf0e6"
dark_background = "#f8e5d5"
darker_background = "#ecd7c7"
lighter_background = "#f2dcca"

foreground = "#3c291a"
dark_foreground = "#706052"
light_foreground = "#5b493a"
bright_foreground = "#201307"

hyprland_active_border = "rgba(a65a3bee) rgba(837655ee) 45deg"
hyprland_inactive_border = "rgba(8a7666aa)"

red = "#983835"
yellow = "#8c6721"
orange = "#97501d"
green = "#657044"
cyan = "#4e7476"
blue = "#84513e"
magenta = "#945463"
brown = "#774826"

bright_red = "#862323"
bright_yellow = "#785506"
bright_green = "#545f32"
bright_cyan = "#3a6264"
bright_blue = "#733f2d"
bright_magenta = "#824252"
