mode = "light"

accent = "#ad5520"
selection = "#ebceb9"
muted = "#877767"

background = "#fcf0e4"
dark_background = "#f4e6d7"
darker_background = "#e8d8c9"
lighter_background = "#eeddcc"

foreground = "#392b1b"
dark_foreground = "#6f6051"
light_foreground = "#594a3b"
bright_foreground = "#1f1308"

hyprland_active_border = "rgba(ad5520ee) rgba(a85556ee) 45deg"
hyprland_inactive_border = "rgba(877767aa)"

red = "#8e392a"
yellow = "#9b6100"
orange = "#974c17"
green = "#676933"
cyan = "#577375"
blue = "#7c533c"
magenta = "#6c3739"
brown = "#774826"

bright_red = "#7c2517"
bright_yellow = "#805000"
bright_green = "#57581e"
bright_cyan = "#435f61"
bright_blue = "#6b422b"
bright_magenta = "#5b262a"
