mode = "light"

accent = "#2b72a8"
selection = "#bfd7eb"
muted = "#6d7c8a"

background = "#e9f4fe"
dark_background = "#ddeaf6"
darker_background = "#cfddea"
lighter_background = "#d3e2f0"

foreground = "#21303c"
dark_foreground = "#576572"
light_foreground = "#414f5b"
bright_foreground = "#0c1721"

hyprland_active_border = "rgba(2b72a8ee) rgba(a06024ee) 45deg"
hyprland_inactive_border = "rgba(6d7c8aaa)"

red = "#9c3c38"
yellow = "#90670e"
orange = "#9b5118"
green = "#367959"
cyan = "#3a7691"
blue = "#1162a6"
magenta = "#656494"
brown = "#774826"

bright_red = "#8a2727"
bright_yellow = "#785402"
bright_green = "#1f6847"
bright_cyan = "#20627d"
bright_blue = "#03518d"
bright_magenta = "#555283"
