mode = "light"

accent = "#ae5507"
selection = "#edceb2"
muted = "#897765"

background = "#fff0e2"
dark_background = "#f7e5d5"
darker_background = "#ebd8c6"
lighter_background = "#f1dcc9"

foreground = "#3b2a19"
dark_foreground = "#706052"
light_foreground = "#5b4939"
bright_foreground = "#1f1307"

hyprland_active_border = "rgba(ae5507ee) rgba(667b3fee) 45deg"
hyprland_inactive_border = "rgba(897765aa)"

red = "#97290a"
yellow = "#906607"
orange = "#934d00"
green = "#5a702d"
cyan = "#726542"
blue = "#875030"
magenta = "#964d54"
brown = "#774826"

bright_red = "#7e1c00"
bright_yellow = "#795500"
bright_green = "#495f16"
bright_cyan = "#615430"
bright_blue = "#753f1d"
bright_magenta = "#843b43"
