mode = "light"

accent = "#a15d3e"
selection = "#e9d0c1"
muted = "#8a7666"

background = "#fdf0e6"
dark_background = "#f8e4d5"
darker_background = "#ecd7c7"
lighter_background = "#f2dcca"

foreground = "#3c291a"
dark_foreground = "#706052"
light_foreground = "#5b493a"
bright_foreground = "#201308"

hyprland_active_border = "rgba(a15d3eee) rgba(a85550ee) 45deg"
hyprland_inactive_border = "rgba(8a7666aa)"

red = "#a5483a"
yellow = "#8e6703"
orange = "#9e5718"
green = "#5d762b"
cyan = "#0d7a76"
blue = "#136b96"
magenta = "#9b4a6c"
brown = "#774826"

bright_red = "#933527"
bright_yellow = "#765607"
bright_green = "#4a630e"
bright_cyan = "#0a6562"
bright_blue = "#005981"
bright_magenta = "#89375b"
