mode = "light"

accent = "#a15d3e"
selection = "#e9d0c1"
muted = "#8a7666"

background = "#fdf0e6"
dark_background = "#f8e4d5"
darker_background = "#ecd7c7"
lighter_background = "#f2dcca"

foreground = "#3c291a"
dark_foreground = "#706052"
light_foreground = "#5b493a"
bright_foreground = "#201308"

hyprland_active_border = "rgba(a15d3eee) rgba(a85550ee) 45deg"
hyprland_inactive_border = "rgba(8a7666aa)"

red = "#9b2742"
yellow = "#9a620b"
orange = "#a1441e"
green = "#5f7339"
cyan = "#7c6d52"
blue = "#884f35"
magenta = "#974e73"
brown = "#774826"

bright_red = "#890732"
bright_yellow = "#825100"
bright_green = "#4e6225"
bright_cyan = "#69593e"
bright_blue = "#773d22"
bright_magenta = "#863b62"
