mode = "dark"

accent = "#81b4f6"
selection = "#2f435b"
muted = "#667584"

background = "#0f171f"
dark_background = "#0b1117"
darker_background = "#080c10"
lighter_background = "#1d2630"

foreground = "#d8e3ee"
dark_foreground = "#8c959f"
light_foreground = "#c0ccd9"
bright_foreground = "#f2f7fd"

hyprland_active_border = "rgba(81b4f6ee) rgba(edd4abee) 45deg"
hyprland_inactive_border = "rgba(667584aa)"

red = "#e6857e"
yellow = "#f7dba1"
orange = "#f4b082"
green = "#82c8b0"
cyan = "#8cdffb"
blue = "#6fa7ee"
magenta = "#8ec5ec"
brown = "#885836"

bright_red = "#f3a29a"
bright_yellow = "#feedc9"
bright_green = "#a3dcc7"
bright_cyan = "#c9effd"
bright_blue = "#8fbdf9"
bright_magenta = "#addbfb"
