mode = "dark"

accent = "#fd923e"
selection = "#5b3216"
muted = "#856b5f"

background = "#1c0d07"
dark_background = "#150a05"
darker_background = "#0e0704"
lighter_background = "#2d1c14"

foreground = "#f0ddd4"
dark_foreground = "#9f8e86"
light_foreground = "#dac6bc"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(fd923eee) rgba(e58870ee) 45deg"
hyprland_inactive_border = "rgba(856b5faa)"

red = "#df6a59"
yellow = "#febd5c"
orange = "#f49251"
green = "#a9ba78"
cyan = "#f0dcb1"
blue = "#e79363"
magenta = "#dc8a90"
brown = "#865634"

bright_red = "#eb8979"
bright_yellow = "#fedbac"
bright_green = "#c1cf99"
bright_cyan = "#feedca"
bright_blue = "#f5ae87"
bright_magenta = "#eaa5aa"
