mode = "dark"

accent = "#fd923e"
selection = "#5b3216"
muted = "#856b5f"

background = "#1c0d07"
dark_background = "#150a05"
darker_background = "#0e0704"
lighter_background = "#2d1c14"

foreground = "#f0ddd4"
dark_foreground = "#9f8e86"
light_foreground = "#dac6bc"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(fd923eee) rgba(e58870ee) 45deg"
hyprland_inactive_border = "rgba(856b5faa)"

red = "#f27e65"
yellow = "#feb76a"
orange = "#fb9a62"
green = "#9bc065"
cyan = "#3bd0c8"
blue = "#5ab5ef"
magenta = "#e487c2"
brown = "#865634"

bright_red = "#fe9d86"
bright_yellow = "#fdd6b0"
bright_green = "#b5d48b"
bright_cyan = "#79e3dc"
bright_blue = "#83cafb"
bright_magenta = "#f3a4d5"
