mode = "dark"

accent = "#f39762"
selection = "#55311e"
muted = "#856b5f"

background = "#170904"
dark_background = "#110703"
darker_background = "#0c0502"
lighter_background = "#28170f"

foreground = "#f0ddd4"
dark_foreground = "#9e8c85"
light_foreground = "#dac6bc"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(f39762ee) rgba(57b6b6ee) 45deg"
hyprland_inactive_border = "rgba(856b5faa)"

red = "#e67d58"
yellow = "#f8c970"
orange = "#f3a35a"
green = "#88c99e"
cyan = "#6cd9d8"
blue = "#6fa7ee"
magenta = "#e5848c"
brown = "#865634"

bright_red = "#f29a7b"
bright_yellow = "#ffe4b4"
bright_green = "#a8ddb9"
bright_cyan = "#98edec"
bright_blue = "#8fbdf9"
bright_magenta = "#f3a0a6"
