mode = "light"

accent = "#98630c"
selection = "#d9d6bb"
muted = "#6f7f72"

background = "#ebf6ec"
dark_background = "#dfede1"
darker_background = "#d1e0d4"
lighter_background = "#d5e5d8"

foreground = "#233226"
dark_foreground = "#59685b"
light_foreground = "#435245"
bright_foreground = "#0e1910"

hyprland_active_border = "rgba(98630cee) rgba(32854aee) 45deg"
hyprland_inactive_border = "rgba(6f7f72aa)"

red = "#9c3428"
yellow = "#976500"
orange = "#9d4d06"
green = "#0c7f3b"
cyan = "#07564b"
blue = "#0a6d4f"
magenta = "#8a4d0c"
brown = "#774826"

bright_red = "#8a1d13"
bright_yellow = "#7d5300"
bright_green = "#056b2f"
bright_cyan = "#07443b"
bright_blue = "#045a40"
bright_magenta = "#733f04"
