mode = "light"

accent = "#657621"
selection = "#d8d7b8"
muted = "#837966"

background = "#f9f2e3"
dark_background = "#f0e8d6"
darker_background = "#e4dac8"
lighter_background = "#e9dfcb"

foreground = "#362d19"
dark_foreground = "#6b6250"
light_foreground = "#554c3a"
bright_foreground = "#1c1507"

hyprland_active_border = "rgba(657621ee) rgba(936907ee) 45deg"
hyprland_inactive_border = "rgba(837966aa)"

red = "#973b24"
yellow = "#8d6902"
orange = "#965200"
green = "#5c771d"
cyan = "#6e6639"
blue = "#3f6c49"
magenta = "#7c4711"
brown = "#774826"

bright_red = "#85260d"
bright_yellow = "#745603"
bright_green = "#4a6400"
bright_cyan = "#5d5526"
bright_blue = "#2c5b38"
bright_magenta = "#683802"
