mode = "dark"

accent = "#a9bb71"
selection = "#3f4123"
muted = "#7b705b"

background = "#161105"
dark_background = "#110d04"
darker_background = "#0b0903"
lighter_background = "#262012"

foreground = "#e8e0d1"
dark_foreground = "#989183"
light_foreground = "#d2cab9"
bright_foreground = "#faf6ef"

hyprland_active_border = "rgba(a9bb71ee) rgba(cc9c42ee) 45deg"
hyprland_inactive_border = "rgba(7b705baa)"

red = "#de826a"
yellow = "#f8ca65"
orange = "#f1a360"
green = "#adca7a"
cyan = "#e7e0b2"
blue = "#85b18e"
magenta = "#dca476"
brown = "#865634"

bright_red = "#ec9e8a"
bright_yellow = "#fee5b1"
bright_green = "#c6df9d"
bright_cyan = "#f6f0ca"
bright_blue = "#a1c5a7"
bright_magenta = "#ecbd97"
