mode = "dark"

accent = "#daa843"
selection = "#4d3816"
muted = "#7f6e5c"

background = "#160d04"
dark_background = "#110a03"
darker_background = "#0b0702"
lighter_background = "#261c10"

foreground = "#ebdfd2"
dark_foreground = "#9a8f84"
light_foreground = "#d5c8ba"
bright_foreground = "#fbf6f0"

hyprland_active_border = "rgba(daa843ee) rgba(e4896aee) 45deg"
hyprland_inactive_border = "rgba(7f6e5caa)"

red = "#eb8370"
yellow = "#f4bd5a"
orange = "#f59e5e"
green = "#97c071"
cyan = "#4cceca"
blue = "#68b3ec"
magenta = "#e08bbf"
brown = "#865634"

bright_red = "#f8a08f"
bright_yellow = "#ffd896"
bright_green = "#b2d493"
bright_cyan = "#80e1de"
bright_blue = "#8dc8f9"
bright_magenta = "#efa7d2"
