mode = "light"

accent = "#78700a"
selection = "#ddd5b6"
muted = "#837968"

background = "#f9f1e6"
dark_background = "#f0e7d9"
darker_background = "#e3dacb"
lighter_background = "#e9dfcf"

foreground = "#362c1c"
dark_foreground = "#6c6252"
light_foreground = "#554c3c"
bright_foreground = "#1c1508"

hyprland_active_border = "rgba(78700aee) rgba(ab5637ee) 45deg"
hyprland_inactive_border = "rgba(837968aa)"

red = "#ac4135"
yellow = "#7c6e00"
orange = "#985a04"
green = "#517a1b"
cyan = "#0d7b7d"
blue = "#0069a3"
magenta = "#9b457f"
brown = "#774826"

bright_red = "#9a2b21"
bright_yellow = "#675b00"
bright_green = "#406603"
bright_cyan = "#076668"
bright_blue = "#005789"
bright_magenta = "#89316f"
