mode = "dark"

accent = "#ecd78a"
selection = "#554c2f"
muted = "#7a735f"

background = "#1a160b"
dark_background = "#141108"
darker_background = "#0d0b06"
lighter_background = "#292519"

foreground = "#e6e1d3"
dark_foreground = "#989487"
light_foreground = "#d0cabb"
bright_foreground = "#f9f7ef"

hyprland_active_border = "rgba(ecd78aee) rgba(d1966dee) 45deg"
hyprland_inactive_border = "rgba(7a735faa)"

red = "#dc8c80"
yellow = "#dec679"
orange = "#e5a772"
green = "#9ebd80"
cyan = "#6ec9c7"
blue = "#7bb1df"
magenta = "#d693b9"
brown = "#885836"

bright_red = "#eaa79c"
bright_yellow = "#f1dd9f"
bright_green = "#b7d29f"
bright_cyan = "#94dddb"
bright_blue = "#9ac6ed"
bright_magenta = "#e6aecd"
