mode = "light"

accent = "#257f2f"
selection = "#c0dbc4"
muted = "#6f7d71"

background = "#ecf5ee"
dark_background = "#e1ece3"
darker_background = "#d3dfd5"
lighter_background = "#d8e4da"

foreground = "#253227"
dark_foreground = "#5a675c"
light_foreground = "#445146"
bright_foreground = "#0f1911"

hyprland_active_border = "rgba(257f2fee) rgba(9a6418ee) 45deg"
hyprland_inactive_border = "rgba(6f7d71aa)"

red = "#942b2b"
yellow = "#6c7501"
orange = "#875503"
green = "#297f0e"
cyan = "#006058"
blue = "#117152"
magenta = "#7a6110"
brown = "#774826"

bright_red = "#821118"
bright_yellow = "#586000"
bright_green = "#1d6a00"
bright_cyan = "#004e47"
bright_blue = "#005f43"
bright_magenta = "#675000"
