mode = "dark"

accent = "#f0995b"
selection = "#57321e"
muted = "#886961"

background = "#1b0a06"
dark_background = "#140805"
darker_background = "#0e0503"
lighter_background = "#2d1813"

foreground = "#f3dbd5"
dark_foreground = "#a18c86"
light_foreground = "#ddc4be"
bright_foreground = "#fdf5f2"

hyprland_active_border = "rgba(f0995bee) rgba(e68677ee) 45deg"
hyprland_inactive_border = "rgba(886961aa)"

red = "#ec8274"
yellow = "#fdb674"
orange = "#f79b70"
green = "#a0be6d"
cyan = "#53cdc8"
blue = "#69b3e9"
magenta = "#e08bbd"
brown = "#865634"

bright_red = "#f8a093"
bright_yellow = "#ffd5af"
bright_green = "#b9d391"
bright_cyan = "#84e0dc"
bright_blue = "#8dc8f6"
bright_magenta = "#efa7d0"
