mode = "dark"

accent = "#f0995b"
selection = "#57321e"
muted = "#886961"

background = "#1b0a06"
dark_background = "#140805"
darker_background = "#0e0503"
lighter_background = "#2d1813"

foreground = "#f3dbd5"
dark_foreground = "#a18c86"
light_foreground = "#ddc4be"
bright_foreground = "#fdf5f2"

hyprland_active_border = "rgba(f0995bee) rgba(e68677ee) 45deg"
hyprland_inactive_border = "rgba(886961aa)"

red = "#da6d5d"
yellow = "#ffbc6a"
orange = "#f0935d"
green = "#abb886"
cyan = "#eddcb9"
blue = "#cf957b"
magenta = "#e9979d"
brown = "#865634"

bright_red = "#e68b7c"
bright_yellow = "#ffdbb2"
bright_green = "#c2cda4"
bright_cyan = "#fbedd0"
bright_blue = "#dfae98"
bright_magenta = "#f8b2b6"
