mode = "light"

accent = "#7c6e40"
selection = "#ddd5c2"
muted = "#82796a"

background = "#f8f2e7"
dark_background = "#efe7db"
darker_background = "#e2dacd"
lighter_background = "#e8dfd1"

foreground = "#352c1e"
dark_foreground = "#6b6253"
light_foreground = "#544c3e"
bright_foreground = "#1c150a"

hyprland_active_border = "rgba(7c6e40ee) rgba(976539ee) 45deg"
hyprland_inactive_border = "rgba(82796aaa)"

red = "#96534b"
yellow = "#90672e"
orange = "#965c3a"
green = "#5d7744"
cyan = "#257a7b"
blue = "#35698b"
magenta = "#8b5575"
brown = "#774826"

bright_red = "#84413a"
bright_yellow = "#7c5211"
bright_green = "#49632f"
bright_cyan = "#086567"
bright_blue = "#20587b"
bright_magenta = "#7a4365"
