mode = "light"

accent = "#7c6e40"
selection = "#ddd5c2"
muted = "#82796a"

background = "#f8f2e7"
dark_background = "#efe7db"
darker_background = "#e2dacd"
lighter_background = "#e8dfd1"

foreground = "#352c1e"
dark_foreground = "#6b6253"
light_foreground = "#544c3e"
bright_foreground = "#1c150a"

hyprland_active_border = "rgba(7c6e40ee) rgba(976539ee) 45deg"
hyprland_inactive_border = "rgba(82796aaa)"

red = "#93453a"
yellow = "#735b01"
orange = "#884f15"
green = "#6c733e"
cyan = "#4e7476"
blue = "#7d6045"
magenta = "#945b63"
brown = "#774826"

bright_red = "#813228"
bright_yellow = "#604b00"
bright_green = "#5a6029"
bright_cyan = "#3a6264"
bright_blue = "#6b4f34"
bright_magenta = "#824953"
