mode = "light"

accent = "#ac5716"
selection = "#eaceb7"
muted = "#877767"

background = "#fcf0e4"
dark_background = "#f4e6d7"
darker_background = "#e8d9c8"
lighter_background = "#edddcc"

foreground = "#392b1b"
dark_foreground = "#6f6151"
light_foreground = "#584a3b"
bright_foreground = "#1e1407"

hyprland_active_border = "rgba(ac5716ee) rgba(906a22ee) 45deg"
hyprland_inactive_border = "rgba(877767aa)"

red = "#a64735"
yellow = "#8f6704"
orange = "#9e5714"
green = "#5a772a"
cyan = "#137b7a"
blue = "#156a99"
magenta = "#964b78"
brown = "#774826"

bright_red = "#943321"
bright_yellow = "#775608"
bright_green = "#47640e"
bright_cyan = "#0f6665"
bright_blue = "#005884"
bright_magenta = "#853867"
