mode = "light"

accent = "#ac5716"
selection = "#eaceb7"
muted = "#877767"

background = "#fcf0e4"
dark_background = "#f4e6d7"
darker_background = "#e8d9c8"
lighter_background = "#edddcc"

foreground = "#392b1b"
dark_foreground = "#6f6151"
light_foreground = "#584a3b"
bright_foreground = "#1e1407"

hyprland_active_border = "rgba(ac5716ee) rgba(906a22ee) 45deg"
hyprland_inactive_border = "rgba(877767aa)"

red = "#933720"
yellow = "#996307"
orange = "#984d0c"
green = "#686b2c"
cyan = "#577375"
blue = "#825336"
magenta = "#733637"
brown = "#774826"

bright_red = "#812207"
bright_yellow = "#7e5106"
bright_green = "#575a14"
bright_cyan = "#435f61"
bright_blue = "#714224"
bright_magenta = "#622427"
