mode = "light"

accent = "#9f5f01"
selection = "#e6d1b4"
muted = "#857868"

background = "#faf1e6"
dark_background = "#f2e7d9"
darker_background = "#e6d9cb"
lighter_background = "#ebdece"

foreground = "#382b1c"
dark_foreground = "#6e6152"
light_foreground = "#574b3c"
bright_foreground = "#1d1409"

hyprland_active_border = "rgba(9f5f01ee) rgba(b24e44ee) 45deg"
hyprland_inactive_border = "rgba(857868aa)"

red = "#a74542"
yellow = "#996304"
orange = "#a45323"
green = "#5c7728"
cyan = "#127b7c"
blue = "#1b699a"
magenta = "#954b7c"
brown = "#774826"

bright_red = "#953130"
bright_yellow = "#7e5104"
bright_green = "#4a640a"
bright_cyan = "#0e6667"
bright_blue = "#085884"
bright_magenta = "#83396b"
