mode = "light"

accent = "#7c61a8"
selection = "#dcd0e9"
muted = "#817686"

background = "#f7effb"
dark_background = "#eee5f2"
darker_background = "#e1d7e6"
lighter_background = "#e7dcec"

foreground = "#342938"
dark_foreground = "#695f6e"
light_foreground = "#534958"
bright_foreground = "#1a131e"

hyprland_active_border = "rgba(7c61a8ee) rgba(8c7349ee) 45deg"
hyprland_inactive_border = "rgba(817686aa)"

red = "#963b63"
yellow = "#856a2d"
orange = "#9a4f34"
green = "#497653"
cyan = "#566f9b"
blue = "#5e599e"
magenta = "#845399"
brown = "#774826"

bright_red = "#842753"
bright_yellow = "#735712"
bright_green = "#366541"
bright_cyan = "#425b87"
bright_blue = "#4e478d"
bright_magenta = "#734188"
