mode = "dark"

accent = "#fe8a88"
selection = "#5a2e2c"
muted = "#866a64"

background = "#1a0a08"
dark_background = "#140806"
darker_background = "#0d0504"
lighter_background = "#2b1815"

foreground = "#f1dcd8"
dark_foreground = "#9f8c89"
light_foreground = "#dcc5c0"
bright_foreground = "#fdf4f3"

hyprland_active_border = "rgba(fe8a88ee) rgba(62b995ee) 45deg"
hyprland_inactive_border = "rgba(866a64aa)"

red = "#e85f61"
yellow = "#f7dba1"
orange = "#f6a067"
green = "#6bcf9d"
cyan = "#ace7cc"
blue = "#5eb7a7"
magenta = "#f496bb"
brown = "#865634"

bright_red = "#f38180"
bright_yellow = "#feedc9"
bright_green = "#93e2b8"
bright_cyan = "#ccfbe5"
bright_blue = "#84cabc"
bright_magenta = "#fdb6d1"
