mode = "light"

accent = "#9b6203"
selection = "#e7d2b3"
muted = "#867867"

background = "#fcf1e4"
dark_background = "#f3e6d7"
darker_background = "#e7d9c8"
lighter_background = "#eddecc"

foreground = "#382b1a"
dark_foreground = "#6e6151"
light_foreground = "#584b3b"
bright_foreground = "#1e1407"

hyprland_active_border = "rgba(9b6203ee) rgba(a26770ee) 45deg"
hyprland_inactive_border = "rgba(867867aa)"

red = "#973f4a"
yellow = "#976500"
orange = "#9e4f28"
green = "#64713d"
cyan = "#605439"
blue = "#8a5434"
magenta = "#9d5874"
brown = "#774826"

bright_red = "#852b39"
bright_yellow = "#7d5300"
bright_green = "#54602a"
bright_cyan = "#504328"
bright_blue = "#794220"
bright_magenta = "#8a4461"
