mode = "dark"

accent = "#fe8f5b"
selection = "#542f1e"
muted = "#806c66"

background = "#120906"
dark_background = "#0e0705"
darker_background = "#090503"
lighter_background = "#211613"

foreground = "#edddd8"
dark_foreground = "#9a8c88"
light_foreground = "#d7c6c1"
bright_foreground = "#fdf5f2"

hyprland_active_border = "rgba(fe8f5bee) rgba(75acd2ee) 45deg"
hyprland_inactive_border = "rgba(806c66aa)"

red = "#e2684a"
yellow = "#ffbc64"
orange = "#f4924d"
green = "#a0bc86"
cyan = "#fdd5b7"
blue = "#7fafe2"
magenta = "#d5848a"
brown = "#865634"

bright_red = "#ee876e"
bright_yellow = "#fedbb0"
bright_green = "#b9d1a4"
bright_cyan = "#feeadb"
bright_blue = "#9dc5ef"
bright_magenta = "#e39fa3"
