mode = "dark"

accent = "#e6d6b3"
selection = "#574e40"
muted = "#807466"

background = "#1f1913"
dark_background = "#17130e"
darker_background = "#100d0a"
lighter_background = "#302921"

foreground = "#e9e0d5"
dark_foreground = "#9c948b"
light_foreground = "#d3c9bd"
bright_foreground = "#fbf6f0"

hyprland_active_border = "rgba(e6d6b3ee) rgba(cf976aee) 45deg"
hyprland_inactive_border = "rgba(807466aa)"

red = "#d4908c"
yellow = "#edbe86"
orange = "#e5a586"
green = "#9fbc8b"
cyan = "#7ec6c6"
blue = "#81b1d5"
magenta = "#d8a0c1"
brown = "#8b5b39"

bright_red = "#e4aaa6"
bright_yellow = "#fed7a9"
bright_green = "#b8d1a8"
bright_cyan = "#a0dada"
bright_blue = "#9fc6e4"
bright_magenta = "#e9bad5"
