mode = "dark"

accent = "#e4a249"
selection = "#45391b"
muted = "#667768"

background = "#071009"
dark_background = "#050c07"
darker_background = "#040805"
lighter_background = "#141f16"

foreground = "#d8e5da"
dark_foreground = "#89948b"
light_foreground = "#c1cfc3"
bright_foreground = "#f2f9f3"

hyprland_active_border = "rgba(e4a249ee) rgba(6fb880ee) 45deg"
hyprland_inactive_border = "rgba(667768aa)"

red = "#e47d6d"
yellow = "#fcbe62"
orange = "#f59b62"
green = "#76cf8a"
cyan = "#95e3d3"
blue = "#65b090"
magenta = "#e0a26f"
brown = "#865634"

bright_red = "#f19a8c"
bright_yellow = "#fedbad"
bright_green = "#9be2a9"
bright_cyan = "#b8f7ea"
bright_blue = "#87c3a8"
bright_magenta = "#f0bb91"
