mode = "dark"

accent = "#e4a249"
selection = "#45391b"
muted = "#667768"

background = "#071009"
dark_background = "#050c07"
darker_background = "#040805"
lighter_background = "#141f16"

foreground = "#d8e5da"
dark_foreground = "#89948b"
light_foreground = "#c1cfc3"
bright_foreground = "#f2f9f3"

hyprland_active_border = "rgba(e4a249ee) rgba(6fb880ee) 45deg"
hyprland_inactive_border = "rgba(667768aa)"

red = "#ec817a"
yellow = "#fbb95e"
orange = "#f99b66"
green = "#82c57e"
cyan = "#3fced2"
blue = "#67b2f1"
magenta = "#e28abe"
brown = "#865634"

bright_red = "#f89f97"
bright_yellow = "#fed7a5"
bright_green = "#a1d99e"
bright_cyan = "#7ae1e4"
bright_blue = "#8cc8fc"
bright_magenta = "#f1a7d1"
