mode = "dark"

accent = "#f1ebd5"
selection = "#53493f"
muted = "#836c61"

background = "#160a05"
dark_background = "#110804"
darker_background = "#0b0503"
lighter_background = "#261811"

foreground = "#efddd5"
dark_foreground = "#9d8d86"
light_foreground = "#d9c6bd"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(f1ebd5ee) rgba(da915fee) 45deg"
hyprland_inactive_border = "rgba(836c61aa)"

red = "#e4877c"
yellow = "#f7ba6f"
orange = "#f29f71"
green = "#a2bd76"
cyan = "#63cbc6"
blue = "#6eb3e2"
magenta = "#dc8fb8"
brown = "#865634"

bright_red = "#f1a399"
bright_yellow = "#fed6a8"
bright_green = "#bbd297"
bright_cyan = "#8edfda"
bright_blue = "#91c8ef"
bright_magenta = "#ebaacc"
