mode = "light"

accent = "#96650a"
selection = "#e3d2b9"
muted = "#84786c"

background = "#f9f1ea"
dark_background = "#f0e7de"
darker_background = "#e3dad0"
lighter_background = "#e9ded4"

foreground = "#362c21"
dark_foreground = "#6c6156"
light_foreground = "#564b40"
bright_foreground = "#1d140c"

hyprland_active_border = "rgba(96650aee) rgba(468062ee) 45deg"
hyprland_inactive_border = "rgba(84786caa)"

red = "#a54743"
yellow = "#92670c"
orange = "#a05622"
green = "#457b3b"
cyan = "#0e7c78"
blue = "#136a9a"
magenta = "#974a77"
brown = "#774826"

bright_red = "#933331"
bright_yellow = "#7a5400"
bright_green = "#2f6724"
bright_cyan = "#086662"
bright_blue = "#005885"
bright_magenta = "#853766"
