mode = "dark"

accent = "#79b8ed"
selection = "#294155"
muted = "#637482"

background = "#0a131a"
dark_background = "#080e14"
darker_background = "#050a0d"
lighter_background = "#18222a"

foreground = "#d7e3ee"
dark_foreground = "#89949d"
light_foreground = "#bfccd8"
bright_foreground = "#f1f8fd"

hyprland_active_border = "rgba(79b8edee) rgba(d39562ee) 45deg"
hyprland_inactive_border = "rgba(637482aa)"

red = "#e6857e"
yellow = "#f4ca84"
orange = "#f3a677"
green = "#8ac8a6"
cyan = "#a2daf6"
blue = "#67aaed"
magenta = "#b2b2e3"
brown = "#865634"

bright_red = "#f3a29a"
bright_yellow = "#fee4ba"
bright_green = "#a9dcc0"
bright_cyan = "#cceeff"
bright_blue = "#8ac0f8"
bright_magenta = "#c9c9f3"
