mode = "light"

accent = "#b14c51"
selection = "#edcbc4"
muted = "#897669"

background = "#feefe5"
dark_background = "#f7e5d9"
darker_background = "#ead7cb"
lighter_background = "#f1dcce"

foreground = "#3b291d"
dark_foreground = "#715f53"
light_foreground = "#5b493d"
bright_foreground = "#201309"

hyprland_active_border = "rgba(b14c51ee) rgba(8c7349ee) 45deg"
hyprland_inactive_border = "rgba(897669aa)"

red = "#982431"
yellow = "#8c6908"
orange = "#984a05"
green = "#497653"
cyan = "#7b6b51"
blue = "#914a56"
magenta = "#7b3b5c"
brown = "#774826"

bright_red = "#86011f"
bright_yellow = "#735609"
bright_green = "#366541"
bright_cyan = "#68593e"
bright_blue = "#803746"
bright_magenta = "#6a294b"
