mode = "dark"

accent = "#e0d653"
selection = "#4e451b"
muted = "#806d5f"

background = "#150c05"
dark_background = "#100904"
darker_background = "#0b0603"
lighter_background = "#261a11"

foreground = "#edded3"
dark_foreground = "#9b8e85"
light_foreground = "#d7c7bc"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(e0d653ee) rgba(d49656ee) 45deg"
hyprland_inactive_border = "rgba(806d5faa)"

red = "#dc785f"
yellow = "#eee354"
orange = "#f5a842"
green = "#a2ce72"
cyan = "#a6daaf"
blue = "#cfab6d"
magenta = "#f5ab78"
brown = "#865634"

bright_red = "#e9957f"
bright_yellow = "#fbf487"
bright_green = "#bde297"
bright_cyan = "#c3eecb"
bright_blue = "#e1c391"
bright_magenta = "#ffc7a2"
