mode = "dark"

accent = "#f9a870"
selection = "#65452e"
muted = "#8e7766"

background = "#2c1e14"
dark_background = "#21170f"
darker_background = "#160f0a"
lighter_background = "#3e2e22"

foreground = "#efded2"
dark_foreground = "#a5958a"
light_foreground = "#d9c7ba"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(f9a870ee) rgba(bf9f6aee) 45deg"
hyprland_inactive_border = "rgba(8e7766aa)"

red = "#e58871"
yellow = "#edc06a"
orange = "#eea366"
green = "#99bf7a"
cyan = "#5eccc9"
blue = "#6eb3e4"
magenta = "#d98fbf"
brown = "#91603e"

bright_red = "#f3a491"
bright_yellow = "#fed994"
bright_green = "#b3d39a"
bright_cyan = "#8bdfdc"
bright_blue = "#91c8f2"
bright_magenta = "#e9aad2"
