mode = "dark"

accent = "#eaddc1"
selection = "#51453a"
muted = "#826c61"

background = "#150a05"
dark_background = "#100804"
darker_background = "#0b0503"
lighter_background = "#251811"

foreground = "#eeded5"
dark_foreground = "#9c8d86"
light_foreground = "#d8c7bd"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(eaddc1ee) rgba(d59466ee) 45deg"
hyprland_inactive_border = "rgba(826c61aa)"

red = "#dc8b87"
yellow = "#f2bc7f"
orange = "#eba27f"
green = "#a2bc80"
cyan = "#74c9c3"
blue = "#78b2da"
magenta = "#d693b7"
brown = "#865634"

bright_red = "#eba6a1"
bright_yellow = "#fed6ab"
bright_green = "#bbd19f"
bright_cyan = "#99ddd8"
bright_blue = "#98c7e9"
bright_magenta = "#e6aecb"
