mode = "dark"

accent = "#c5b164"
selection = "#423920"
muted = "#7a7061"

background = "#0f0a05"
dark_background = "#0b0804"
darker_background = "#080503"
lighter_background = "#1e1910"

foreground = "#e8e0d5"
dark_foreground = "#968f86"
light_foreground = "#d1c9bd"
bright_foreground = "#faf6ef"

hyprland_active_border = "rgba(c5b164ee) rgba(d49375ee) 45deg"
hyprland_inactive_border = "rgba(7a7061aa)"

red = "#ba8466"
yellow = "#e2c97d"
orange = "#d2a56e"
green = "#aab97f"
cyan = "#fef0d8"
blue = "#e7e0b2"
magenta = "#d29c8a"
brown = "#865634"

bright_red = "#ca9c83"
bright_yellow = "#f5e0a3"
bright_green = "#c1ce9e"
bright_cyan = "#fdecd0"
bright_blue = "#f6f0ca"
bright_magenta = "#e2b5a5"
