mode = "dark"

accent = "#c5b164"
selection = "#423920"
muted = "#7a7061"

background = "#0f0a05"
dark_background = "#0b0804"
darker_background = "#080503"
lighter_background = "#1e1910"

foreground = "#e8e0d5"
dark_foreground = "#968f86"
light_foreground = "#d1c9bd"
bright_foreground = "#faf6ef"

hyprland_active_border = "rgba(c5b164ee) rgba(d49375ee) 45deg"
hyprland_inactive_border = "rgba(7a7061aa)"

red = "#e48876"
yellow = "#e1c66a"
orange = "#eba564"
green = "#a0bd75"
cyan = "#60cbcb"
blue = "#6db4e2"
magenta = "#dc8fba"
brown = "#865634"

bright_red = "#f1a494"
bright_yellow = "#f4dd94"
bright_green = "#b9d297"
bright_cyan = "#8cdfde"
bright_blue = "#90c9f0"
bright_magenta = "#ebabce"
