mode = "dark"

accent = "#8ad0eb"
selection = "#2c444f"
muted = "#667381"

background = "#070d13"
dark_background = "#050a0e"
darker_background = "#04070a"
lighter_background = "#141b23"

foreground = "#d9e2ed"
dark_foreground = "#89919a"
light_foreground = "#c1ccd7"
bright_foreground = "#f2f7fd"

hyprland_active_border = "rgba(8ad0ebee) rgba(cd995cee) 45deg"
hyprland_inactive_border = "rgba(667381aa)"

red = "#d78e88"
yellow = "#f8c885"
orange = "#eda983"
green = "#85cfbb"
cyan = "#81daef"
blue = "#73b1e6"
magenta = "#aeb3e4"
brown = "#865634"

bright_red = "#e6a8a2"
bright_yellow = "#ffe3be"
bright_green = "#a7e3d2"
bright_cyan = "#adeefe"
bright_blue = "#94c7f3"
bright_magenta = "#c6caf3"
