mode = "dark"

accent = "#f69557"
selection = "#59331d"
muted = "#856b5f"

background = "#1c0d07"
dark_background = "#150a05"
darker_background = "#0e0704"
lighter_background = "#2d1c14"

foreground = "#f0ddd4"
dark_foreground = "#9f8e86"
light_foreground = "#dac6bc"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(f69557ee) rgba(99ae76ee) 45deg"
hyprland_inactive_border = "rgba(856b5faa)"

red = "#da6f54"
yellow = "#f4c26a"
orange = "#eb9855"
green = "#a4bb7c"
cyan = "#ebddb9"
blue = "#ce9677"
magenta = "#e49a9f"
brown = "#865634"

bright_red = "#e68d76"
bright_yellow = "#fddda6"
bright_green = "#bcd09c"
bright_cyan = "#f9eed0"
bright_blue = "#deaf95"
bright_magenta = "#f4b4b8"
