mode = "light"

accent = "#9c548d"
selection = "#e8cdd6"
muted = "#8a756f"

background = "#feefea"
dark_background = "#f6e4df"
darker_background = "#ead7d1"
lighter_background = "#f0dbd5"

foreground = "#3b2923"
dark_foreground = "#725e58"
light_foreground = "#5b4842"
bright_foreground = "#20120e"

hyprland_active_border = "rgba(9c548dee) rgba(986600ee) 45deg"
hyprland_inactive_border = "rgba(8a756faa)"

red = "#96364c"
yellow = "#90670e"
orange = "#9c4c24"
green = "#4e7646"
cyan = "#7e5f47"
blue = "#6a5988"
magenta = "#964c7f"
brown = "#774826"

bright_red = "#84213b"
bright_yellow = "#785402"
bright_green = "#3c6533"
bright_cyan = "#6d4e35"
bright_blue = "#594877"
bright_magenta = "#84396f"
