mode = "dark"

accent = "#ecdeaa"
selection = "#554935"
muted = "#826d5f"

background = "#1a0f07"
dark_background = "#140b05"
darker_background = "#0d0804"
lighter_background = "#2a1d14"

foreground = "#eeded4"
dark_foreground = "#9d8f86"
light_foreground = "#d8c7bc"
bright_foreground = "#fcf5f1"

hyprland_active_border = "rgba(ecdeaaee) rgba(d9906fee) 45deg"
hyprland_inactive_border = "rgba(826d5faa)"

red = "#dc8d7e"
yellow = "#ddc67a"
orange = "#e4a872"
green = "#9ebd82"
cyan = "#71c9c9"
blue = "#7ab2dc"
magenta = "#d693b7"
brown = "#865634"

bright_red = "#eba89b"
bright_yellow = "#f0dd9f"
bright_green = "#b8d2a1"
bright_cyan = "#97dddd"
bright_blue = "#99c7eb"
bright_magenta = "#e6aecb"
