mode = "dark"

accent = "#ecdeaa"
selection = "#554935"
muted = "#826d5f"

background = "#1a0f07"
dark_background = "#140b05"
darker_background = "#0d0804"
lighter_background = "#2a1d14"

foreground = "#eeded4"
dark_foreground = "#9d8f86"
light_foreground = "#d8c7bc"
bright_foreground = "#fcf5f1"

hyprland_active_border = "rgba(ecdeaaee) rgba(d9906fee) 45deg"
hyprland_inactive_border = "rgba(826d5faa)"

red = "#da8375"
yellow = "#f6dd90"
orange = "#efae76"
green = "#adc08f"
cyan = "#b3d9db"
blue = "#c9a187"
magenta = "#e4a2b0"
brown = "#865634"

bright_red = "#e89e92"
bright_yellow = "#feeebc"
bright_green = "#c5d5ac"
bright_cyan = "#cfeff0"
bright_blue = "#dbb9a3"
bright_magenta = "#f4bcc8"
