mode = "light"

accent = "#b15306"
selection = "#eecdb2"
muted = "#897765"

background = "#fff0e2"
dark_background = "#f7e5d5"
darker_background = "#ebd8c6"
lighter_background = "#f1dcc9"

foreground = "#3b2a19"
dark_foreground = "#706052"
light_foreground = "#5b4939"
bright_foreground = "#1f1307"

hyprland_active_border = "rgba(b15306ee) rgba(008282ee) 45deg"
hyprland_inactive_border = "rgba(897765aa)"

red = "#9f3300"
yellow = "#8f6807"
orange = "#945308"
green = "#347a51"
cyan = "#0b7b7b"
blue = "#2460a7"
magenta = "#9b3a48"
brown = "#774826"

bright_red = "#842a00"
bright_yellow = "#765508"
bright_green = "#19673e"
bright_cyan = "#086666"
bright_blue = "#094e96"
bright_magenta = "#892537"
