mode = "light"

accent = "#b84b03"
selection = "#ebccb6"
muted = "#86776b"

background = "#faf0e8"
dark_background = "#f2e6dc"
darker_background = "#e5d9ce"
lighter_background = "#ebded2"

foreground = "#382b1f"
dark_foreground = "#6e6055"
light_foreground = "#574a3f"
bright_foreground = "#1e140b"

hyprland_active_border = "rgba(b84b03ee) rgba(3c78a0ee) 45deg"
hyprland_inactive_border = "rgba(86776baa)"

red = "#9a2501"
yellow = "#996300"
orange = "#974b08"
green = "#567039"
cyan = "#825d3f"
blue = "#346698"
magenta = "#8f3f49"
brown = "#774826"

bright_red = "#7f1b00"
bright_yellow = "#7f5100"
bright_green = "#455f26"
bright_cyan = "#714c2d"
bright_blue = "#1f5587"
bright_magenta = "#7d2c38"
