mode = "light"

accent = "#856c08"
selection = "#e2d4b4"
muted = "#867867"

background = "#fcf1e4"
dark_background = "#f3e6d7"
darker_background = "#e7d9c8"
lighter_background = "#eddecc"

foreground = "#382b1a"
dark_foreground = "#6e6151"
light_foreground = "#584b3b"
bright_foreground = "#1e1407"

hyprland_active_border = "rgba(856c08ee) rgba(a7593dee) 45deg"
hyprland_inactive_border = "rgba(867867aa)"

red = "#ab422e"
yellow = "#876b09"
orange = "#9c5907"
green = "#56791c"
cyan = "#137b7b"
blue = "#036a9f"
magenta = "#9b457b"
brown = "#774826"

bright_red = "#992c18"
bright_yellow = "#6f5808"
bright_green = "#466505"
bright_cyan = "#0e6667"
bright_blue = "#075885"
bright_magenta = "#89316a"
