mode = "light"

accent = "#926706"
selection = "#e3d3b5"
muted = "#847869"

background = "#faf1e6"
dark_background = "#f1e7da"
darker_background = "#e4dacb"
lighter_background = "#eadecf"

foreground = "#372c1d"
dark_foreground = "#6d6152"
light_foreground = "#564b3d"
bright_foreground = "#1d1409"

hyprland_active_border = "rgba(926706ee) rgba(4e7a82ee) 45deg"
hyprland_inactive_border = "rgba(847869aa)"

red = "#a5483f"
yellow = "#8f6704"
orange = "#9f561c"
green = "#56782d"
cyan = "#0e7c78"
blue = "#16699b"
magenta = "#974a77"
brown = "#774826"

bright_red = "#93342d"
bright_yellow = "#775609"
bright_green = "#436512"
bright_cyan = "#076663"
bright_blue = "#015885"
bright_magenta = "#853766"
