mode = "dark"

accent = "#ecdeb1"
selection = "#58513e"
muted = "#817566"

background = "#1f1a11"
dark_background = "#17140d"
darker_background = "#100d09"
lighter_background = "#30291f"

foreground = "#e9e0d4"
dark_foreground = "#9c958a"
light_foreground = "#d3c9bc"
bright_foreground = "#fbf6f0"

hyprland_active_border = "rgba(ecdeb1ee) rgba(ca9971ee) 45deg"
hyprland_inactive_border = "rgba(817566aa)"

red = "#dc8c7f"
yellow = "#f8dc90"
orange = "#f1b27e"
green = "#bcc490"
cyan = "#b3d9db"
blue = "#c8ab90"
magenta = "#e7acb3"
brown = "#8b5b39"

bright_red = "#eaa79b"
bright_yellow = "#ffedc0"
bright_green = "#d3daaf"
bright_cyan = "#cfeff0"
bright_blue = "#dbc2ac"
bright_magenta = "#f8c6cc"
