mode = "light"

accent = "#237692"
selection = "#c0d8e5"
muted = "#707c88"

background = "#ecf3fc"
dark_background = "#e0eaf4"
darker_background = "#d3dde7"
lighter_background = "#d7e2ed"

foreground = "#242f3b"
dark_foreground = "#596571"
light_foreground = "#434e5a"
bright_foreground = "#0e1720"

hyprland_active_border = "rgba(237692ee) rgba(9a6418ee) 45deg"
hyprland_inactive_border = "rgba(707c88aa)"

red = "#9e4e46"
yellow = "#946614"
orange = "#9d582c"
green = "#4f7939"
cyan = "#0a7b80"
blue = "#0c6c91"
magenta = "#914f7a"
brown = "#774826"

bright_red = "#8c3b34"
bright_yellow = "#7c5308"
bright_green = "#3c6623"
bright_cyan = "#09666b"
bright_blue = "#065a7a"
bright_magenta = "#803c69"
