mode = "light"

accent = "#237692"
selection = "#c0d8e5"
muted = "#707c88"

background = "#ecf3fc"
dark_background = "#e0eaf4"
darker_background = "#d3dde7"
lighter_background = "#d7e2ed"

foreground = "#242f3b"
dark_foreground = "#596571"
light_foreground = "#434e5a"
bright_foreground = "#0e1720"

hyprland_active_border = "rgba(237692ee) rgba(9a6418ee) 45deg"
hyprland_inactive_border = "rgba(707c88aa)"

red = "#8f4843"
yellow = "#936513"
orange = "#95542c"
green = "#267c69"
cyan = "#07798d"
blue = "#21689c"
magenta = "#616595"
brown = "#774826"

bright_red = "#7e3632"
bright_yellow = "#7c5409"
bright_green = "#086755"
bright_cyan = "#056576"
bright_blue = "#00568b"
bright_magenta = "#505484"
