mode = "light"

accent = "#ab5809"
selection = "#eccfb5"
muted = "#8c7767"

background = "#fef0e5"
dark_background = "#f9e4d4"
darker_background = "#edd7c6"
lighter_background = "#f3dbc9"

foreground = "#3d2919"
dark_foreground = "#706052"
light_foreground = "#5c493a"
bright_foreground = "#201308"

hyprland_active_border = "rgba(ab5809ee) rgba(b14f41ee) 45deg"
hyprland_inactive_border = "rgba(8c7767aa)"

red = "#98271b"
yellow = "#9a6208"
orange = "#9c4600"
green = "#616d3a"
cyan = "#645432"
blue = "#884f35"
magenta = "#7e303a"
brown = "#774826"

bright_red = "#860700"
bright_yellow = "#7f5005"
bright_green = "#505c26"
bright_cyan = "#544320"
bright_blue = "#773d22"
bright_magenta = "#6c1d2a"
