mode = "dark"

accent = "#fe8a88"
selection = "#592f2d"
muted = "#846b66"

background = "#190b09"
dark_background = "#130807"
darker_background = "#0d0605"
lighter_background = "#291917"

foreground = "#f0dcd9"
dark_foreground = "#9e8d8a"
light_foreground = "#dac5c1"
bright_foreground = "#fdf4f3"

hyprland_active_border = "rgba(fe8a88ee) rgba(77b779ee) 45deg"
hyprland_inactive_border = "rgba(846b66aa)"

red = "#e65d64"
yellow = "#f2cc7a"
orange = "#f59555"
green = "#7fc581"
cyan = "#c9d0a3"
blue = "#7ab39a"
magenta = "#ef90ae"
brown = "#865634"

bright_red = "#f38183"
bright_yellow = "#fee5b3"
bright_green = "#9fd9a0"
bright_cyan = "#e0e6c1"
bright_blue = "#99c7b1"
bright_magenta = "#fdadc5"
