mode = "light"

accent = "#9d6002"
selection = "#e8d0b0"
muted = "#877764"

background = "#fdf0e1"
dark_background = "#f5e6d4"
darker_background = "#e9d9c5"
lighter_background = "#efddc8"

foreground = "#3a2b18"
dark_foreground = "#6e6151"
light_foreground = "#594a38"
bright_foreground = "#1e1406"

hyprland_active_border = "rgba(9d6002ee) rgba(857447ee) 45deg"
hyprland_inactive_border = "rgba(877764aa)"

red = "#ac403e"
yellow = "#9a6206"
orange = "#a7511e"
green = "#59781b"
cyan = "#097a75"
blue = "#076a9e"
magenta = "#9a467e"
brown = "#774826"

bright_red = "#9a2a2c"
bright_yellow = "#805002"
bright_green = "#486404"
bright_cyan = "#036561"
bright_blue = "#005886"
bright_magenta = "#88336d"
