mode = "light"

accent = "#9d6002"
selection = "#e8d0b0"
muted = "#877764"

background = "#fdf0e1"
dark_background = "#f5e6d4"
darker_background = "#e9d9c5"
lighter_background = "#efddc8"

foreground = "#3a2b18"
dark_foreground = "#6e6151"
light_foreground = "#594a38"
bright_foreground = "#1e1406"

hyprland_active_border = "rgba(9d6002ee) rgba(857447ee) 45deg"
hyprland_inactive_border = "rgba(877764aa)"

red = "#a03114"
yellow = "#996302"
orange = "#9d4d00"
green = "#6d6e2e"
cyan = "#625431"
blue = "#895530"
magenta = "#964d54"
brown = "#774826"

bright_red = "#8a1f00"
bright_yellow = "#7f5100"
bright_green = "#5c5d17"
bright_cyan = "#524320"
bright_blue = "#78441b"
bright_magenta = "#843b43"
