mode = "dark"

accent = "#fe8b83"
selection = "#592f2b"
muted = "#846b66"

background = "#190b09"
dark_background = "#130807"
darker_background = "#0d0605"
lighter_background = "#291917"

foreground = "#f0dcd9"
dark_foreground = "#9e8d8a"
light_foreground = "#dac5c1"
bright_foreground = "#fdf4f3"

hyprland_active_border = "rgba(fe8b83ee) rgba(d39562ee) 45deg"
hyprland_inactive_border = "rgba(846b66aa)"

red = "#f9786a"
yellow = "#ffb850"
orange = "#fd995c"
green = "#9bc063"
cyan = "#33d0cd"
blue = "#56b5f0"
magenta = "#e886bc"
brown = "#865634"

bright_red = "#ff9c8f"
bright_yellow = "#fdd7a6"
bright_green = "#b5d489"
bright_cyan = "#75e3e0"
bright_blue = "#80cafb"
bright_magenta = "#f6a4d0"
