mode = "dark"

accent = "#fe8b83"
selection = "#592f2b"
muted = "#846b66"

background = "#190b09"
dark_background = "#130807"
darker_background = "#0d0605"
lighter_background = "#291917"

foreground = "#f0dcd9"
dark_foreground = "#9e8d8a"
light_foreground = "#dac5c1"
bright_foreground = "#fdf4f3"

hyprland_active_border = "rgba(fe8b83ee) rgba(d39562ee) 45deg"
hyprland_inactive_border = "rgba(846b66aa)"

red = "#e65e59"
yellow = "#ffa659"
orange = "#f68252"
green = "#99c68f"
cyan = "#fccabd"
blue = "#e1878e"
magenta = "#f18db5"
brown = "#865634"

bright_red = "#f3827a"
bright_yellow = "#fec79c"
bright_green = "#b5daad"
bright_cyan = "#fee9e4"
bright_blue = "#efa3a8"
bright_magenta = "#ffaacb"
