mode = "dark"

accent = "#bca1ed"
selection = "#403551"
muted = "#776d7f"

background = "#100b14"
dark_background = "#0c080f"
darker_background = "#08060a"
lighter_background = "#1f1924"

foreground = "#e5deec"
dark_foreground = "#948e9a"
light_foreground = "#cfc7d6"
bright_foreground = "#f9f5fc"

hyprland_active_border = "rgba(bca1edee) rgba(d6917aee) 45deg"
hyprland_inactive_border = "rgba(776d7faa)"

red = "#dd7aa2"
yellow = "#efcc83"
orange = "#f69d7e"
green = "#94c5a4"
cyan = "#b4cbf9"
blue = "#9d9be7"
magenta = "#d695e4"
brown = "#865634"

bright_red = "#ea97b8"
bright_yellow = "#fee5b1"
bright_green = "#b1d9bd"
bright_cyan = "#d4e2ff"
bright_blue = "#b4b3f3"
bright_magenta = "#e7b1f3"
