mode = "dark"

accent = "#bca1ed"
selection = "#403551"
muted = "#776d7f"

background = "#100b14"
dark_background = "#0c080f"
darker_background = "#08060a"
lighter_background = "#1f1924"

foreground = "#e5deec"
dark_foreground = "#948e9a"
light_foreground = "#cfc7d6"
bright_foreground = "#f9f5fc"

hyprland_active_border = "rgba(bca1edee) rgba(d6917aee) 45deg"
hyprland_inactive_border = "rgba(776d7faa)"

red = "#eb8372"
yellow = "#f0bf59"
orange = "#f49f5d"
green = "#8ec372"
cyan = "#3acfd2"
blue = "#60b3f0"
magenta = "#d08fda"
brown = "#865634"

bright_red = "#f8a091"
bright_yellow = "#ffd88d"
bright_green = "#abd795"
bright_cyan = "#78e2e4"
bright_blue = "#87c9fb"
bright_magenta = "#e1abe9"
