mode = "dark"

accent = "#db997b"
selection = "#54362a"
muted = "#886b64"

background = "#1f0f0b"
dark_background = "#170b08"
darker_background = "#100806"
lighter_background = "#301d19"

foreground = "#f1dcd6"
dark_foreground = "#a18e89"
light_foreground = "#dbc5bf"
bright_foreground = "#fdf5f2"

hyprland_active_border = "rgba(db997bee) rgba(dc8c85ee) 45deg"
hyprland_inactive_border = "rgba(886b64aa)"

red = "#e07081"
yellow = "#fdbc6f"
orange = "#f6936f"
green = "#acc188"
cyan = "#ecdcc1"
blue = "#cf957b"
magenta = "#e89dc0"
brown = "#865634"

bright_red = "#ed8e9a"
bright_yellow = "#fddbb4"
bright_green = "#c4d6a7"
bright_cyan = "#faedd6"
bright_blue = "#dfae98"
bright_magenta = "#f8b8d5"
