mode = "dark"

accent = "#db997b"
selection = "#54362a"
muted = "#886b64"

background = "#1f0f0b"
dark_background = "#170b08"
darker_background = "#100806"
lighter_background = "#301d19"

foreground = "#f1dcd6"
dark_foreground = "#a18e89"
light_foreground = "#dbc5bf"
bright_foreground = "#fdf5f2"

hyprland_active_border = "rgba(db997bee) rgba(dc8c85ee) 45deg"
hyprland_inactive_border = "rgba(886b64aa)"

red = "#e48877"
yellow = "#ecc06a"
orange = "#eea269"
green = "#a2bd77"
cyan = "#66cbc6"
blue = "#6db4df"
magenta = "#e08ead"
brown = "#865634"

bright_red = "#f1a495"
bright_yellow = "#fdd894"
bright_green = "#bbd298"
bright_cyan = "#90dfda"
bright_blue = "#90c9ed"
bright_magenta = "#efaac3"
