mode = "dark"

accent = "#e2a355"
selection = "#553b20"
muted = "#826f5f"

background = "#1e130b"
dark_background = "#170e08"
darker_background = "#0f0a06"
lighter_background = "#2f2218"

foreground = "#edded3"
dark_foreground = "#9e9187"
light_foreground = "#d7c7bb"
bright_foreground = "#fcf5f0"

hyprland_active_border = "rgba(e2a355ee) rgba(e7acb3ee) 45deg"
hyprland_inactive_border = "rgba(826f5faa)"

red = "#e1878e"
yellow = "#fcbe62"
orange = "#f79e75"
green = "#b1bf8c"
cyan = "#eaddc1"
blue = "#d59c7d"
magenta = "#f4acc7"
brown = "#885836"

bright_red = "#efa3a8"
bright_yellow = "#fedbad"
bright_green = "#c9d4aa"
bright_cyan = "#f9edd6"
bright_blue = "#e5b59b"
bright_magenta = "#fecadd"
