mode = "dark"

accent = "#e9cd9d"
selection = "#5d4e3a"
muted = "#887765"

background = "#271d13"
dark_background = "#1d160e"
darker_background = "#140f0a"
lighter_background = "#382d21"

foreground = "#ebdfd2"
dark_foreground = "#a19589"
light_foreground = "#d5c8ba"
bright_foreground = "#fbf6f0"

hyprland_active_border = "rgba(e9cd9dee) rgba(d1966dee) 45deg"
hyprland_inactive_border = "rgba(887765aa)"

red = "#d79080"
yellow = "#e3c288"
orange = "#e1a87f"
green = "#9fbc8b"
cyan = "#7ec6c5"
blue = "#80b2d4"
magenta = "#cf97b7"
brown = "#905f3d"

bright_red = "#e6aa9c"
bright_yellow = "#f5daaa"
bright_green = "#b9d1a8"
bright_cyan = "#a0dad9"
bright_blue = "#9ec7e4"
bright_magenta = "#e0b1cb"
