mode = "light"

accent = "#00769d"
selection = "#b7d8e9"
muted = "#707b8b"

background = "#ebf3fe"
dark_background = "#dfeaf7"
darker_background = "#d2dceb"
lighter_background = "#d6e2f1"

foreground = "#242f3d"
dark_foreground = "#596473"
light_foreground = "#434e5c"
bright_foreground = "#0e1721"

hyprland_active_border = "rgba(00769dee) rgba(9c630aee) 45deg"
hyprland_inactive_border = "rgba(707b8baa)"

red = "#9c3b40"
yellow = "#90670e"
orange = "#9c501d"
green = "#2a7a62"
cyan = "#077797"
blue = "#315cae"
magenta = "#6c599e"
brown = "#774826"

bright_red = "#8a262f"
bright_yellow = "#785402"
bright_green = "#046750"
bright_cyan = "#00637e"
bright_blue = "#1f499e"
bright_magenta = "#5c478d"
