mode = "dark"

accent = "#dd96cd"
selection = "#4e3346"
muted = "#806b74"

background = "#160c11"
dark_background = "#11090d"
darker_background = "#0b0609"
lighter_background = "#261a1f"

foreground = "#ecdce3"
dark_foreground = "#9b8d93"
light_foreground = "#d7c5cc"
bright_foreground = "#fcf4f8"

hyprland_active_border = "rgba(dd96cdee) rgba(cd9a50ee) 45deg"
hyprland_inactive_border = "rgba(806b74aa)"

red = "#de7d8d"
yellow = "#f4ca84"
orange = "#f2a07c"
green = "#9dc494"
cyan = "#f8d7be"
blue = "#b1a1d1"
magenta = "#e79bce"
brown = "#865634"

bright_red = "#eb9aa6"
bright_yellow = "#fee4ba"
bright_green = "#b7d9b0"
bright_cyan = "#ffeada"
bright_blue = "#c6b9e1"
bright_magenta = "#f6b7e0"
