mode = "light"

accent = "#9f5f04"
selection = "#e8d1b3"
muted = "#867867"

background = "#fcf1e4"
dark_background = "#f3e6d7"
darker_background = "#e7d9c8"
lighter_background = "#eddecc"

foreground = "#382b1a"
dark_foreground = "#6e6151"
light_foreground = "#584b3b"
bright_foreground = "#1e1407"

hyprland_active_border = "rgba(9f5f04ee) rgba(b24d49ee) 45deg"
hyprland_inactive_border = "rgba(867867aa)"

red = "#98392d"
yellow = "#976505"
orange = "#9b4f13"
green = "#687031"
cyan = "#457673"
blue = "#855738"
magenta = "#75373e"
brown = "#774826"

bright_red = "#862419"
bright_yellow = "#7c5306"
bright_green = "#585f1b"
bright_cyan = "#306460"
bright_blue = "#744625"
bright_magenta = "#64262e"
