mode = "light"

accent = "#7f6a0c"
selection = "#d9d1b4"
muted = "#7e7668"

background = "#f3eee4"
dark_background = "#eae4d8"
darker_background = "#ddd7ca"
lighter_background = "#e3dbce"

foreground = "#342d1f"
dark_foreground = "#6a6254"
light_foreground = "#544c3e"
bright_foreground = "#1b150a"

hyprland_active_border = "rgba(7f6a0cee) rgba(a15d3eee) 45deg"
hyprland_inactive_border = "rgba(7e7668aa)"

red = "#7c4626"
yellow = "#6d5807"
orange = "#774e13"
green = "#606e31"
cyan = "#7c6847"
blue = "#4f481a"
magenta = "#643422"
brown = "#774826"

bright_red = "#6b3512"
bright_yellow = "#5a4803"
bright_green = "#505d1c"
bright_cyan = "#695634"
bright_blue = "#403804"
bright_magenta = "#542311"
