mode = "light"

accent = "#b94259"
selection = "#edcac9"
muted = "#8a756b"

background = "#fcf0e9"
dark_background = "#f8e4da"
darker_background = "#ecd6cc"
lighter_background = "#f2dbd0"

foreground = "#3c291f"
dark_foreground = "#725e55"
light_foreground = "#5c483f"
bright_foreground = "#20120b"

hyprland_active_border = "rgba(b94259ee) rgba(a25282ee) 45deg"
hyprland_inactive_border = "rgba(8a756baa)"

red = "#9b1b38"
yellow = "#9a620b"
orange = "#a14113"
green = "#577535"
cyan = "#92625a"
blue = "#8a446e"
magenta = "#7f1945"
brown = "#774826"

bright_red = "#850029"
bright_yellow = "#825100"
bright_green = "#466421"
bright_cyan = "#7f4f47"
bright_blue = "#78325d"
bright_magenta = "#6c0035"
