mode = "dark"

accent = "#fd8c7b"
selection = "#4d3332"
muted = "#647480"

background = "#091016"
dark_background = "#070c11"
darker_background = "#05080b"
lighter_background = "#171f26"

foreground = "#d7e3ec"
dark_foreground = "#89939b"
light_foreground = "#c0cdd6"
bright_foreground = "#f1f8fd"

hyprland_active_border = "rgba(fd8c7bee) rgba(78afbcee) 45deg"
hyprland_inactive_border = "rgba(647480aa)"

red = "#e36650"
yellow = "#efcc83"
orange = "#ee9b57"
green = "#a0c398"
cyan = "#99d5ed"
blue = "#86a4e4"
magenta = "#eb9dbb"
brown = "#865634"

bright_red = "#ee8672"
bright_yellow = "#fee5b1"
bright_green = "#bbd8b4"
bright_cyan = "#b9eaff"
bright_blue = "#a1bbf0"
bright_magenta = "#fab8d1"
