mode = "light"

accent = "#707300"
selection = "#cdd9c0"
muted = "#697f80"

background = "#e7f6f6"
dark_background = "#dbeded"
darker_background = "#cde0e0"
lighter_background = "#d1e5e6"

foreground = "#1c3233"
dark_foreground = "#536869"
light_foreground = "#3d5152"
bright_foreground = "#08191a"

hyprland_active_border = "rgba(707300ee) rgba(008282ee) 45deg"
hyprland_inactive_border = "rgba(697f80aa)"

red = "#9c3d30"
yellow = "#787006"
orange = "#905806"
green = "#507b06"
cyan = "#006058"
blue = "#067482"
magenta = "#935619"
brown = "#774826"

bright_red = "#8a281d"
bright_yellow = "#645d05"
bright_green = "#406500"
bright_cyan = "#034d47"
bright_blue = "#09616d"
bright_magenta = "#804500"
