mode = "light"

accent = "#b84b17"
selection = "#eeccb8"
muted = "#8a7666"

background = "#fdf0e6"
dark_background = "#f8e5d5"
darker_background = "#ecd7c7"
lighter_background = "#f2dcca"

foreground = "#3c291a"
dark_foreground = "#706052"
light_foreground = "#5b493a"
bright_foreground = "#201307"

hyprland_active_border = "rgba(b84b17ee) rgba(9b6406ee) 45deg"
hyprland_inactive_border = "rgba(8a7666aa)"

red = "#9c1e1a"
yellow = "#845200"
orange = "#8f4004"
green = "#816c07"
cyan = "#574223"
blue = "#793b1c"
magenta = "#974964"
brown = "#774826"

bright_red = "#860307"
bright_yellow = "#6d4400"
bright_green = "#6c5a00"
bright_cyan = "#473211"
bright_blue = "#682904"
bright_magenta = "#853753"
