mode = "dark"

accent = "#e89b80"
selection = "#4a3027"
muted = "#7f6d67"

background = "#0c0604"
dark_background = "#090503"
darker_background = "#060302"
lighter_background = "#1b130f"

foreground = "#ecded9"
dark_foreground = "#978c88"
light_foreground = "#d6c7c1"
bright_foreground = "#fdf5f2"

hyprland_active_border = "rgba(e89b80ee) rgba(ca9971ee) 45deg"
hyprland_inactive_border = "rgba(7f6d67aa)"

red = "#c07a70"
yellow = "#eab583"
orange = "#d79677"
green = "#afa985"
cyan = "#afcacc"
blue = "#f1cab9"
magenta = "#c49397"
brown = "#865634"

bright_red = "#cf938b"
bright_yellow = "#facea5"
bright_green = "#c4bfa1"
bright_cyan = "#c9e0e1"
bright_blue = "#fde5da"
bright_magenta = "#d5abaf"
