mode = "dark"

accent = "#ebd6a3"
selection = "#514331"
muted = "#826d5f"

background = "#150a04"
dark_background = "#100803"
darker_background = "#0b0502"
lighter_background = "#251810"

foreground = "#eeded4"
dark_foreground = "#9c8d85"
light_foreground = "#d8c7bc"
bright_foreground = "#fcf5f1"

hyprland_active_border = "rgba(ebd6a3ee) rgba(f07f77ee) 45deg"
hyprland_inactive_border = "rgba(826d5faa)"

red = "#e47d6d"
yellow = "#f4dca1"
orange = "#f0ad78"
green = "#a7c28c"
cyan = "#a6d6d2"
blue = "#d09e83"
magenta = "#efa3a8"
brown = "#865634"

bright_red = "#f19a8c"
bright_yellow = "#feedc5"
bright_green = "#c0d7aa"
bright_cyan = "#c4ebe8"
bright_blue = "#e0b7a0"
bright_magenta = "#febec2"
