mode = "dark"

accent = "#b4b943"
selection = "#374120"
muted = "#5f7778"

background = "#061212"
dark_background = "#050e0e"
darker_background = "#030909"
lighter_background = "#132122"

foreground = "#d4e5e6"
dark_foreground = "#869595"
light_foreground = "#bccfd0"
bright_foreground = "#f0f9f9"

hyprland_active_border = "rgba(b4b943ee) rgba(57b6b6ee) 45deg"
hyprland_inactive_border = "rgba(5f7778aa)"

red = "#e68677"
yellow = "#ede361"
orange = "#faaf58"
green = "#a2ce72"
cyan = "#89e5d9"
blue = "#65c1d1"
magenta = "#e0a26f"
brown = "#865634"

bright_red = "#f3a395"
bright_yellow = "#fbf48f"
bright_green = "#bde297"
bright_cyan = "#b0f9ef"
bright_blue = "#8dd5e2"
bright_magenta = "#f0bb91"
