mode = "dark"

accent = "#6bb9f8"
selection = "#24415a"
muted = "#637385"

background = "#09121c"
dark_background = "#070e15"
darker_background = "#05090e"
lighter_background = "#17212d"

foreground = "#d7e3f0"
dark_foreground = "#89949f"
light_foreground = "#bfccda"
bright_foreground = "#f2f7fd"

hyprland_active_border = "rgba(6bb9f8ee) rgba(ead5abee) 45deg"
hyprland_inactive_border = "rgba(637385aa)"

red = "#e6857e"
yellow = "#f7dba1"
orange = "#f4b082"
green = "#82c8b0"
cyan = "#79e4f0"
blue = "#64a9f3"
magenta = "#87c8e8"
brown = "#865634"

bright_red = "#f3a29a"
bright_yellow = "#feedc9"
bright_green = "#a3dcc7"
bright_cyan = "#aef6ff"
bright_blue = "#88bffd"
bright_magenta = "#a8ddf8"
