mode = "light"

accent = "#77700b"
selection = "#ded5b5"
muted = "#857867"

background = "#fbf1e5"
dark_background = "#f3e6d8"
darker_background = "#e6d9ca"
lighter_background = "#ecdecd"

foreground = "#382b1b"
dark_foreground = "#6e6151"
light_foreground = "#574b3b"
bright_foreground = "#1e1408"

hyprland_active_border = "rgba(77700bee) rgba(a16007ee) 45deg"
hyprland_inactive_border = "rgba(857867aa)"

red = "#973219"
yellow = "#787003"
orange = "#895605"
green = "#507b06"
cyan = "#447a51"
blue = "#7a5707"
magenta = "#743800"
brown = "#774826"

bright_red = "#831e01"
bright_yellow = "#645d02"
bright_green = "#406500"
bright_cyan = "#2f673e"
bright_blue = "#664703"
bright_magenta = "#5d2c00"
