mode = "light"

accent = "#77700b"
selection = "#ded5b5"
muted = "#857867"

background = "#fbf1e5"
dark_background = "#f3e6d8"
darker_background = "#e6d9ca"
lighter_background = "#ecdecd"

foreground = "#382b1b"
dark_foreground = "#6e6151"
light_foreground = "#574b3b"
bright_foreground = "#1e1408"

hyprland_active_border = "rgba(77700bee) rgba(a16007ee) 45deg"
hyprland_inactive_border = "rgba(857867aa)"

red = "#ac4134"
yellow = "#816e00"
orange = "#9a5a09"
green = "#55791e"
cyan = "#007c79"
blue = "#09699f"
magenta = "#9d4578"
brown = "#774826"

bright_red = "#9a2b20"
bright_yellow = "#6a5a00"
bright_green = "#436405"
bright_cyan = "#0c6563"
bright_blue = "#005787"
bright_magenta = "#8b3167"
