mode = "light"

accent = "#aa590c"
selection = "#ebcfb2"
muted = "#887764"

background = "#fdf0e1"
dark_background = "#f5e6d4"
darker_background = "#e9d8c5"
lighter_background = "#efddc8"

foreground = "#3a2b18"
dark_foreground = "#6e6151"
light_foreground = "#594a38"
bright_foreground = "#1e1406"

hyprland_active_border = "rgba(aa590cee) rgba(8c6b2fee) 45deg"
hyprland_inactive_border = "rgba(887764aa)"

red = "#994211"
yellow = "#7b5703"
orange = "#894f04"
green = "#717232"
cyan = "#577274"
blue = "#6c441f"
magenta = "#692e25"
brown = "#774826"

bright_red = "#843200"
bright_yellow = "#674700"
bright_green = "#5d5e18"
bright_cyan = "#436061"
bright_blue = "#5c330a"
bright_magenta = "#581d15"
