mode = "dark"

accent = "#ed9a67"
selection = "#573723"
muted = "#836e60"

background = "#1c1109"
dark_background = "#150d07"
darker_background = "#0e0905"
lighter_background = "#2d1f17"

foreground = "#eeded4"
dark_foreground = "#9e9087"
light_foreground = "#d8c7bc"
bright_foreground = "#fcf5f1"

hyprland_active_border = "rgba(ed9a67ee) rgba(c29e61ee) 45deg"
hyprland_inactive_border = "rgba(836e60aa)"

red = "#d77b64"
yellow = "#fbbd6e"
orange = "#ec9b65"
green = "#b2b77b"
cyan = "#b5d1d2"
blue = "#c9997c"
magenta = "#e3a09f"
brown = "#885836"

bright_red = "#e49783"
bright_yellow = "#fedab0"
bright_green = "#c8cc9b"
bright_cyan = "#d0e7e8"
bright_blue = "#dab19a"
bright_magenta = "#f3bab9"
